
% -------------------------------------------
% 
%  Fenetre d'affichage des donnees de la base
%
% -------------------------------------------

parameters;

global_rep;

for jj = 1:nbfic_MLT_COMPLET -1

      clatn = sprintf('%7.3f',north_lat_complet(jj));
      clats = sprintf('%7.3f',south_lat_complet(jj));
      clonw = sprintf('%8.3f',west_lon_complet(jj));
      clone = sprintf('%8.3f',east_lon_complet(jj));
      
      ic = length(deblank(project_complet(jj,:)));
      project_complet(jj,ic+1:16) = '.';

%      camp_dates_lat_long_type(jj,:) = [project_complet(jj,1:16),blanks(8),start_date_complet
%(jj,7:8),'/',start_date_complet(jj,5:6),'/',start_date_complet(jj,1:4),blanks(8),stop_date_complet
%(jj,7:8),'/',stop_date_complet(jj,5:6),'/',stop_date_complet(jj,1:4),blanks(8),clatn,blanks(5),clats,blanks
%(8),clonw,blanks(8),clone,blanks(8),data_type_complet(jj,:)];

      camp_dates_lat_long_type(jj,:) = [project_complet(jj,1:16),blanks(8),start_date_complet(jj,7:8),'/',start_date_complet(jj,5:6),'/',start_date_complet(jj,1:4),blanks(8),stop_date_complet(jj,7:8),'/',stop_date_complet(jj,5:6),'/',stop_date_complet(jj,1:4),blanks(8),clatn,blanks(5),clats,blanks(8),clonw,blanks(8),clone,blanks(8)];

end

if  strcmp(project_complet(1,1:4),'H2V2')
        nomfenetre = 'AFFICHAGE DES DONNEES DES BASES ANNUELLES H2V2 et LPO';
     else
        nomfenetre = 'AFFICHAGE DES DONNEES DE LA BASE HYDROCEAN-LPO';
end

[m,n] = size(camp_dates_lat_long_type);

figa = figure('Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'Name',nomfenetre, ...
	'NumberTitle','off', ...
	'Position',[200 100 900 800]);


% type de donnees-campagnes-dates-latitude-longitude
% --------------------------------------------------

uicontrol('Parent',figa, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
        'String', camp_dates_lat_long_type(1:m,1:n), ...
	'FontSize',10, ...
	'Position',[0.04 0.3 0.95 0.6], ...
	'Style','listbox', ...
        'Value',1);


% campagne
% --------

uicontrol('Parent',figa, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.001 0.925 0.26 0.06], ...
	'String','Campagne', ...
	'Style','text');

% date debut
% ----------

uicontrol('Parent',figa, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'Position',[0.16 0.925 0.28 0.06], ...
	'String','Entre le  et le', ...
	'Style','text');



% positions
% ---------

uicontrol('Parent',figa, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontSize',11, ...
	'HorizontalAlignment','left', ...
	'Position',[0.38 0.925 0.20 0.06], ...
	'Style','text');



uicontrol('Parent',figa, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontSize',11, ...
	'HorizontalAlignment','left', ...
	'Position',[0.55 0.925 0.15 0.06], ...
	'Style','text');

uicontrol('Parent',figa, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'Position',[0.65 0.925 0.25 0.06], ...
	'String','Type', ...
	'Style','text');





if nargout > 0, fig = figa; end
