%-----------------------------------------------------------------------------------
%  Projet POMME
%  ------------
%  Version: 1.0
%  ------------
%  Creation : Octobre 2001 /  C.Grit
%  Modification : Juin 2002
%                                            
%----------------------------------------------------------------------------
%  Traitement des parametres choisis par l'utilisateur
%----------------------------------------------------------------------------
%
%  Le resultat du choix de l'utilisateur donne les parametres suivants :
%
%  1 - dates_extract : first_day,first_month,first_year,last_day,last_month,last_year
%  2 - zone geographique traitee : 
%	 lat_extract_min,lat_extract_max,lon_extract_min,lon_extract_max
%  3 - immersion d'extraction : imm_extract
%  4 - parametres a ecrire    : param_extract
%----------------------------------------------------------------------------


% Intitule de la fonction
%------------------------

function choix_param(start_date_complet, stop_date_complet);

parameters;

global h_PP h_PPC;


mois_extract = '';

nb_par_extract = 1;
param_extract = 'DEPH';


% liste des mois 
%---------------

list_month = strvcat('01','02','03','04','05','06','07','08','09','10','11','12');

list_day = strvcat('01','02','03','04','05','06','07','08','09','10','11','12', ...
                   '13','14','15','16','17','18','19','20','21','22','23','24', ...
                   '25','26','27','28','29','30','31');


% constitution de la liste des annees possibles en fonction 
% des dates debut et fin de campagne de toute la base
% ----------------------------------------------------------

date_deb_toutes = str2num(start_date_complet(:,1:4));
date_fin_toutes = str2num(stop_date_complet(:,1:4));

list_year_num  =[min(date_deb_toutes):1:max(date_fin_toutes)];
for i = 1:length(list_year_num)
  list_year(i,:) = num2str(list_year_num(i));
end

list_year = char(list_year);

% les valeurs par defaut de la zone d'extraction = tout l'Ocean
%--------------------------------------------------------------

lat_extract_min = -80 ;

lat_extract_max =  89.95;

lon_extract_min = -110;

lon_extract_max = 50;

fig_import = figure('Units','normalized', ...
    'Color',[0.8 0.8 0.8], ...
    'Name','CHOIX DES PARAMETRES POUR L''EXTRACTION', ...
    'Position',[0.02 0.15 0.656 0.65], ...
    'NumberTitle','off',...
    'MenuBar','none');


%=====================================================
% 1 - choisir la date des donnees
%=====================================================

% date de debut
%---------------

checkp = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global periode checkm;',...
		    'periode = ''1'';', ...
        'set(findobj(gcbf,''Tag'',''periode_mois''),''Value'',0);'],...
	'Position',[0.01 0.9 0.03 0.03], ...
        'Tag','periode_an', ...
        'Style','CheckBox');

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.04 0.85 0.1 0.08], ...
	'String','Periode ', ...
	'Style','text');

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.18 0.85 0.07 0.08], ...
	'String','entre le', ...
	'Style','text');

h1 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
        'Callback',['global list_day first_day;',...
                    'j = get(gco,''Value'');', ...
                    'first_day=str2num(list_day(j,:));'],...
	'Min',1, ...
	'Position',[0.27 0.9 0.08 0.04], ...
	'String',list_day,...
	'Style','popupmenu',...
	'Value',1);

h2 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
        'Callback',['global list_month first_month;',...
                    'i = get(gco,''Value'');', ...
  		    'first_month=str2num(list_month(i,:));'],...
	'Min',1, ...
	'Position',[0.35 0.9 0.08 0.04], ...
	'String',list_month,...
	'Style','popupmenu',...
	'Value',1);


h3 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
        'Callback',['global list_year first_year;',...
                    'i = get(gco,''Value'');', ...
                    'first_year=str2num(list_year(i,:));'], ...
	'Min',1, ...
	'Position',[0.43 0.9 0.08 0.04], ...
        'String', list_year, ...
	'Style','popupmenu',...
        'Value',1);

% date de fin
%-------------
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.18 0.85 0.05 0.05], ...
	'String','et le', ...
	'Style','text');

h4 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
        'Callback',['global list_day last_day;',...
                    'i = get(gco,''Value'');', ...
                    'last_day=str2num(list_day(i,:));'], ...
	'Min',1, ...
	'Position',[0.27 0.85 0.08 0.04], ...
	'String',list_day,...
	'Style','popupmenu',...
	'Value',length(list_day));

h5 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
        'Callback',['global list_month last_month;',...
                    'i = get(gco,''Value'');', ...
                    'last_month=str2num(list_month(i,:));'], ...
	'Min',1, ...
	'Position',[0.35 0.85 0.08 0.04], ...
	'String',list_month,...
	'Style','popupmenu',...
	'Value',length(list_month));
	
h6 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
        'Callback',['global list_year last_year;',...
                    'i = get(gco,''Value'');', ...
                    'last_year=str2num(list_year(i,:));'], ...
	'Min',1, ...
	'Position',[0.43 0.85 0.08 0.04], ...
	'Style','popupmenu', ...
        'String', list_year, ...
        'Value',length(list_year));

% --------------
% choix des mois
% --------------

checkm = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global periode checkp;',...
		    'periode = ''0'';', ...
                    'set(findobj(gcbf,''Tag'',''periode_an''),''Value'',0);'],...
	'Position',[0.01 0.7 0.03 0.03], ...
        'Tag','periode_mois', ...
        'Style','CheckBox');

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.05 0.7 0.05 0.03], ...
	'String','Mois', ...
	'Style','text');


% mois 1
% ------
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.25 0.73 0.03 0.03], ...
	'String','01', ...
	'Style','text');

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global mois_extract;',...
		     'mois_extract= strvcat(mois_extract,''01'');'],...
	'Position',[0.25 0.7 0.03 0.03], ...
        'Style','CheckBox');

% mois 2
% ------
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.30 0.73 0.03 0.03], ...
	'String','02', ...
	'Style','text');


uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global mois_extract;',...
		     'mois_extract= strvcat(mois_extract,''02'');'],...
	'Position',[0.30 0.7 0.03 0.03], ...
        'Style','CheckBox');

%mois 3
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.35 0.73 0.03 0.03], ...
	'String','03', ...
	'Style','text');


uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global mois_extract;',...
		     'mois_extract= strvcat(mois_extract,''03'');'],...
	'Position',[0.35 0.7 0.03 0.03], ...
        'Style','CheckBox');

%mois 4
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.40 0.73 0.03 0.03], ...
	'String','04', ...
	'Style','text');


uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global mois_extract;',...
		     'mois_extract= strvcat(mois_extract,''04'');'],...
	'Position',[0.40 0.7 0.03 0.03], ...
        'Style','CheckBox');

%mois 5
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.45 0.73 0.03 0.03], ...
	'String','05', ...
	'Style','text');


uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global mois_extract;',...
		     'mois_extract= strvcat(mois_extract,''05'');'],...
	'Position',[0.45 0.7 0.03 0.03], ...
        'Style','CheckBox');

%mois 6
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.50 0.73 0.03 0.03], ...
	'String','06', ...
	'Style','text');


uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global mois_extract;',...
		     'mois_extract= strvcat(mois_extract,''06'');'],...
	'Position',[0.50 0.7 0.03 0.03], ...
        'Style','CheckBox');

%mois 7
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.25 0.63 0.03 0.03], ...
	'String','07', ...
	'Style','text');


uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global mois_extract;',...
		     'mois_extract= strvcat(mois_extract,''07'');'],...
	'Position',[0.25 0.6 0.03 0.03], ...
        'Style','CheckBox');

%mois 8
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.30 0.63 0.03 0.03], ...
	'String','08', ...
	'Style','text');


uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global mois_extract;',...
		     'mois_extract= strvcat(mois_extract,''08'');'],...
	'Position',[0.30 0.6 0.03 0.03], ...
        'Style','CheckBox');

%mois 9
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.35 0.63 0.03 0.03], ...
	'String','09', ...
	'Style','text');


uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global mois_extract;',...
		     'mois_extract= strvcat(mois_extract,''09'');'],...
	'Position',[0.35 0.6 0.03 0.03], ...
        'Style','CheckBox');

%mois 10
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.40 0.63 0.03 0.03], ...
	'String','10', ...
	'Style','text');


uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global mois_extract;',...
		     'mois_extract= strvcat(mois_extract,''10'');'],...
	'Position',[0.40 0.6 0.03 0.03], ...
        'Style','CheckBox');

%mois 11
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.45 0.63 0.03 0.03], ...
	'String','11', ...
	'Style','text');


uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global mois_extract;',...
		     'mois_extract= strvcat(mois_extract,''11'');'],...
	'Position',[0.45 0.6 0.03 0.03], ...
        'Style','CheckBox');

%mois 12
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.50 0.63 0.03 0.03], ...
	'String','12', ...
	'Style','text');


uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global mois_extract;',...
		     'mois_extract= strvcat(mois_extract,''12'');'],...
	'Position',[0.50 0.6 0.03 0.03], ...
        'Style','CheckBox');

	

%=====================================================
% 2 - choisir la zone geographique voulue
%=====================================================

% en latitude
%-------------
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.65 0.45 0.06 0.04], ...
	'String','Nord ',...
	'Style','text');
	

h1 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'FontSize',10, ...
	'Callback',['global lat_extract_max;',...
		    'lat_extract_max=str2num(get(gco,''String''));'],...
	'Min',1, ...
	'Position',[0.65 0.40 0.06 0.04], ...
        'String',lat_extract_max, ...
        'HorizontalAlignment','center', ...
        'Style','edit');

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.65 0.25 0.06 0.04], ...
	'String','Sud ',...
	'Style','text');
	

h1 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'Callback',['global lat_extract_min;',...
		    'lat_extract_min=str2num(get(gco,''String''));'],...
	'Min',1, ...
	'FontSize',10, ... 
        'HorizontalAlignment','center', ...
	'Position',[0.65 0.30 0.06 0.04], ...
        'String',lat_extract_min, ...
        'Style','edit');

% en longitude
%--------------
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.48 0.35 0.06 0.04], ...
	'String','Ouest ',...
	'Style','text');
	

h1 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'FontSize',10, ...
	'Callback',['global lon_extract_min;',...
		    'lon_extract_min=str2num(get(gco,''String''));'],...
	'Min',1, ...
	'Position',[0.55 0.35 0.06 0.04], ...
        'HorizontalAlignment','center', ...
        'String',lon_extract_min, ...
        'Style','edit');
	 
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.82 0.35 0.06 0.04], ...
	'String','Est ',...
	'Style','text');
	

h1 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'FontSize',10, ...
	'Callback',['global lon_extract_max;',...
		    'lon_extract_max=str2num(get(gco,''String''));'],...
	'Min',1, ...
	'Position',[0.75 0.35 0.06 0.04], ...
        'String',lon_extract_max, ...
        'HorizontalAlignment','center', ...
        'Style','edit');



%==============================================================================
% 4 - choisir la profondeur desiree suivant les niveaux de grille multi-profil
%     (intervalle)
%==============================================================================

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.01 0.44 0.3 0.087], ...
	'String','Immersion ',...
	'Style','text');
	

h1 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'FontSize',11, ...
	'Callback',['global imm_extract_min;',... 
		    'imm_extract_min=str2num(get(gco,''String''));'],...
	'Min',1, ...
	'Position',[0.25 0.5 0.08 0.05], ...
        'Style','edit');


h1 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'FontSize',11, ...
	'Callback',['global imm_extract_max;',... 
		    'imm_extract_max=str2num(get(gco,''String''));'],...
	'Min',1, ...
	'Position',[0.33 0.5 0.08 0.05], ...
        'Style','edit');

%=========================================
% choix des parametres a extraire
%=========================================

ligpp = [];
% attention : ajout sans reflechir ......................;
list_param = ['DEPH';'PRES';'TEMP';'PSAL';'TPOT';'SIGI';'SIG0';'SIG1';'SI15'; ...
             'SSDG';'SIG2';'SIG3';'SIG4';'SIG5';'SIG6';'BRV2';'VORP';'GAMM';'DYNH';'OXYL';'OXYK'];
for i = 1:length(list_param)
     presence_param(i) = ' ';
end

if (length(list_param) > 0)
	
	for i=1:length(list_param)
		lig1pp = sprintf('%1c%s', presence_param (i), list_param(i, :));
		if (i == 1)
			ligpp = lig1pp;
		else
			ligpp = strvcat(ligpp, lig1pp);
		end
	end
end

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.25 0.43 0.13 0.05], ...
	'String','PARAMETRES',...
	'Style','text');
	

h_PP = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'Callback',['hydro_selectparam'],...
	'Position',[0.12 0.1 0.1 0.33], ...
        'String',ligpp, ...
        'Max',length(ligpp), ...
        'Style','ListBox');
	
h_PPC = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'Callback',[''],...
	'Position',[0.3 0.1 0.1 0.33], ...
        'String',param_extract, ...
        'Max',length(param_extract), ...
        'Style','ListBox');

% bouton Aide parametres

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.2 0.04 0.1 0.05], ...
        'Callback','aide_hydro(5);', ...
	'String','Aide');

	


%=====================================================
%   push OK
%=====================================================

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.5 0.06 0.139 0.05], ...
        'Callback',['parameters;',...
        'messok = '''';', ...
        'verif_choix_param(messok);', ...
        'if  ~isempty(messok),', ... 
        '     h=warndlg(messok,''Attention'');', ...
        '     waitfor(h);', ...
        '  else,', ...
	'    close;',...
	'end;'],...
	'String','OK',...
	'Style','Pushbutton');
	

%=====================================================
% 9 - push Annuler
%=====================================================

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.7 0.06 0.139 0.05], ...
        'Callback','close;', ...
	'String','Annuler');

uiwait(fig_import)
