function   choix_rep_ficmltnc(rep_defaut);

% ----------------------------------------------------------
%
%  choix_rep_ficmltnc : C.Lagadec   - Mai 2005
%
%  choix du repertoire de creation du fichier Multistation cree
%        du nom de fichier
%        du nom de projet
%
% fonction appelee par hydro_creat_netcdf
%
% ---------------------------------------------------------

global ficmlt_nc  project rep_ecr;

a = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'Name','Choix du repertoire de creation', ...
	'NumberTitle','off', ...
	'Position',[0.44 0.5 0.45 0.22]);


% String OK
% ---------

uicontrol('Parent',a , ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'ListboxTop',0, ...
        'CallBack',['global rep_ecr rep_defaut;', ...
                    'if isempty(rep_ecr),', ...
                           'rep_ecr=rep_defaut;', ...
                    'end;', ...
                    'if rep_ecr(end) ~= ''/'',', ...
                                'rep_ecr = [rep_ecr ''/''];', ...
                    'end;', ...
                    'close'], ...
	'Position',[0.13 0.1 0.22 0.16], ...
	'String','Ok', ...
        'Style','PushButton');

% repertoire de creation
% ----------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'Callback',['global rep_ecr,', ...
                    'rep_ecr=get(gco,''String''),'], ...
	'FontSize',11, ...
	'Position',[0.40 0.75 0.60 0.14], ...
	'String',rep_defaut,...
        'HorizontalAlignment','left', ...
	'Style','edit');


% nom du fichier
% --------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',['global ficmlt_nc,fic=get(gco,''String''),', ...
                    'ir = length(fic),', ...
                    'if  ~strcmp(fic(ir-1:ir), ''nc''),', ...
                              'ficmlt_nc = [fic ''_DEPH.nc''],', ...
                    'end'], ...
	'FontSize',11, ...
	'Position',[0.40 0.55 0.60 0.14], ...
        'HorizontalAlignment','left', ...
	'Style','edit');


% nom du projet
% --------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','global project,project = get(gco,''String'');', ...
	'FontSize',11, ...
	'Position',[0.40 0.35 0.60 0.14], ...
        'HorizontalAlignment','left', ...
	'Style','edit');


% Pushbutton de sortie d'ecran
% ----------------------------

% -> Annuler

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','close', ...
	'FontSize',13, ...
	'Position',[0.73 0.1 0.22 0.16], ...
	'String','Annuler');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...	
        'Position',[0.03 0.78 0.37 0.11], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'String','Repertoire de creation', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...	
	'Position',[0.03 0.58 0.37 0.11], ...
	'String','Nom du fichier cree ', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...	
	'Position',[0.03 0.38 0.37 0.11], ...
	'String','Nom du projet ', ...
	'Style','text');


uiwait;
