%--------------------------------------------------------------------------
%  Creation : juillet 2005 /  T. Loaec
%                                            
%  Le resultat du choix de l'utilisateur donne le parametre suivant :
%
% nocletri
%--------------------------------------------------------------------------


% Intitule de la fonction
%------------------------

function  inventaire_tri(nbcamp);

global nocletri indtri;

nocletri = 1;
indtri = 0;

% liste des tris possibles
%-------------------------

list_tri = strvcat('Nom de fichier Netcdf (par defaut)','Longitude','Latitude','Date');


fig_import = figure('Units','normalized', ...
    'Color',[0.8 0.8 0.8], ...
    'Name','Tri et creation de l''inventaire Stations', ...
    'Position',[0.5 0.6 0.3 0.3], ...
    'NumberTitle','off',...
    'MenuBar','none');


%=====================================================
% 1 - choisir le critère
%=====================================================

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
        'HorizontalAlignment','left', ...
	'Position',[0.01 0.55 0.239 0.08], ...
	'String','Criteres de tri', ...
	'Style','text');

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.01 0.75 0.6 0.1], ...
        'HorizontalAlignment','left', ...
	'String','Nombre de campagnes traitees  ', ...
	'Style','text');

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
	'FontSize',11, ...
	'Position',[0.7 0.75 0.17 0.1], ...
        'String',nbcamp, ...
        'HorizontalAlignment','center', ...
        'Style','edit');

h1 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
        'FontSize',11, ...
        'Callback',['global nocletri;',...
        'nocletri= get(gco,''Value'');'],...
	'Min',1, ...
	'Position',[0.28 0.5 0.7 0.16], ...
	'String',list_tri,...
	'Style','popupmenu',...
	'Value',1);


%=====================================================
%   push OK
%=====================================================

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.28 0.2 0.16 0.1], ...
	'String','OK',... 
        'Callback','global indtri;indtri = 0;close;', ...
	'Style','Pushbutton');

%=====================================================
% 9 - push Annuler
%=====================================================

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.48 0.2 0.16 0.1], ...
        'Callback','global indtri;indtri = 1;close;', ...
	'String','Annuler');

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.68 0.2 0.16 0.1], ...
        'Callback','global indtri;indtri=1;close;', ...
	'String','Fin');

uiwait(fig_import);
