
function indtrait = inventaire_faccueilnew;

global indtrait;

indtrait = 0;

fig_import = figure('Units','normalized', ...
    'Color',[0.8 0.8 0.8], ...
    'Name','Accueil Inventaire', ...
    'Position',[0.5 0.6 0.4 0.3], ...
    'NumberTitle','off',...
    'MenuBar','none');



uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.3 0.8 0.2 0.1], ...
	'String','Bonjour ', ...
	'Style','text');

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
        'HorizontalAlignment','left', ...
	'Position',[0.18 0.6 0.6 0.1], ...
	'String','Le fichier Inventaire Campagne n''existe pas.', ...
	'Style','text');

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
        'HorizontalAlignment','left', ...
	'Position',[0.18 0.5 0.4 0.1], ...
	'String','Voulez-vous le créer ?', ...
	'Style','text');





%=====================================================
%   push Creation
%=====================================================

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.1 0.2 0.16 0.1], ...
        'Callback',['global indtrait; indtrait=0;close;inventaire_extract_C;'],...
	'String','Creation',...
	'Style','Pushbutton');
	

%=====================================================
% 9 - push Quitter
%=====================================================

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.5 0.2 0.16 0.1], ...
        'Callback',['global indtrait; indtrait = 1; close;'], ...
	'String','Quitter');

uiwait(fig_import)
