
function indtrait2 = inventaire_fmodifcamp;

global indtrait2;

indtrait2 = 0;

fig_import = figure('Units','normalized', ...
    'Color',[0.8 0.8 0.8], ...
    'Name','Modification Inventaire Campagne', ...
    'Position',[0.5 0.6 0.4 0.3], ...
    'NumberTitle','off',...
    'MenuBar','none');

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
        'HorizontalAlignment','left', ...
	'Position',[0.18 0.7 0.6 0.1], ...
	'String','Le fichier Inventaire Campagne est cree.', ...
	'Style','text');

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.18 0.5 0.5 0.1], ...
        'HorizontalAlignment','left', ...
	'String','Vous pouvez le modifier si necessaire ', ... 
	'Style','text');



uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.18 0.4 0.4 0.1], ...
	'String','avant de poursuivre. ', ... 
	'Style','text');



%=====================================================
%   push Mise à jour
%=====================================================

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.1 0.2 0.16 0.1], ...
        'Callback',['global indtrait2; indtrait2 = 0;', ...
                    'inventaire_modif_C;'],...
	'String','Modification',...
	'Style','Pushbutton');
	

%=====================================================
% 9 - push Continuer
%=====================================================

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.3 0.2 0.16 0.1], ...
        'Callback','global indtrait2; indtrait2 = 0; close;', ...
	'String','Continuer');

%=====================================================
% 9 - push Quitter
%=====================================================

uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.5 0.2 0.16 0.1], ...
        'Callback',['global indtrait2; indtrait2 = 1; close;'], ...
	'String','Quitter');

uiwait(fig_import)
