


			%----------------------------------------%
                        %                                        %
	        	%  TRACE DE SECTIONS A PARTIR DE FICHIER %
                        %          MULTISTATION NETCDF           %
        		%----------------------------------------%



globalVarEtiquni ;
globalajo ;
globalRepDef ;
globalVarDef ;
globalVarASCI ;
globalVMLT ;

global type ;


init_cre ;


NOMPROG = 'trace_section';


f = figure('Units','normalized', ...
           'Color',[0.8 0.8 0.8], ...
           'Name','TRACE SECTIONS', ...
           'NumberTitle','off', ...
	   'Position',[0.45 0.81 0.54 0.12], ...
           'MenuBar','none');



% ==============================================================

% CONFIGURATION
% ---------------

h1=uimenu(f,'Label','Configuration');

% sous-menu du menu Configuration : il permet a l'utilisateur de lire des
% fichiers qui ne sont pas dans son repertoire courant, et d'ecrire
% les resultats obtenus dans un autre repertoire.
% -------------------------------------------------------------------------

uimenu(h1,'Label','Environnement de travail ...',...
                'Separator', 'off', ...
                'Callback','choix_envir_cli');



% ==================================================================

% CHOIX DES FICHIERS
% ------------------

h3 = uimenu(f,'Label','Fichiers');
uimenu(h3,'Label','Fichier Multistation ...',...
                'Separator', 'off', ...
                'Callback','choix_envir_cli');

uimenu(h3,'Label','Fichier Paramètres ...',...
                'Separator', 'off', ...
                'Callback','choix_envir_cli');
uimenu(h3,'Label','Fichier Isolignes ...',...
                'Separator', 'off', ...
                'Callback','choix_envir_cli');

%=====================================================================

% PARAMETRAGE
% -----------

h4 = uimenu(f,'Label','Parametres');

% sous-menu du menu Parametrage
% -----------------------------

% sous-menu qui permet a l'utilisateur de changer les valeurs min et/ou max
% et le pas d'echantillonnage de la pression(parametre de reference par 
% defaut), et qui permet egalement de changer le parametre de reference,
% ainsi que les valeurs min et max et le pas.
% **************************************************************************

uimenu(h4,'Label','Parametre de reference ...', ...
		'Separator','on', ...
		'Callback',['if (isempty(NBFILES)),', ...
			    	'h = warndlg(''Vous devez d''''abord choisir des stations'',''Attention'') ;', ...
			    	'waitfor(h),', ...
			    'else,param_ref_mlt ;', ...
			    	'pass_ref = 1;', ...	
			    'end']) ;

% sous-menu qui permet a l'utilisateur de choisir des parametres physiques
% ************************************************************************

uimenu(h4,'Label','Choix des parametres physiques ...', ...
		'Separator','off', ...
		'Callback',['if (isempty(NBFILES)),', ...
			    'h = warndlg(''Vous devez d''''abord choisir des stations'',''Attention'') ;', ...
		            'waitfor(h),', ...    
			    'else,choix_param_phys;', ...
			    'pass_par = 1;', ...
		            'end']) ;




% =======================================================================

% CREATION DES FICHIERS
% --------------------

h5 = uimenu(f,'Label','Creation des Fichiers ');

% sous-menu du menu Creations des fichiers
% -----------------------------------------

% sous-menu qui permet a l'utilisateur de contrôler tous les choix qu'il
% a pu faire auparavant et de modifier certains de ces choix, ou de creer
% directement son fichier multistation.
% ************************************************************************

uimenu(h5,'Label','Recapitulatif ...', ...
             'CallBack',['if ( isempty(pass_ref) & isempty(pass_par) ),', ...
				'h = questdlg(''Vous desirez creer un fichier multistation ayant par defaut tous les parametres physiques existant dans les fichiers unistation que vous avez choisis et ayant egalement par defaut la pression comme parametre de reference.'',''Message'',''Oui'',''Non'',''Non'');', ...
				'if strcmp(h,''Oui''),', ...
					'VALMIN = PMINTOT;', ...
					'VALMAX = PMAXTOT;', ...
					'NB_NIV = ((PMAXTOT-PMINTOT) / XET(27)) + 1;', ...
					'ECHANT_REF = XET(27);', ...
					'CODES_PARAMP_CHOISI = CODPARP_TOT;', ...
					'CODES_PARAMC_CHOISI = CODPARC_TOT;', ...
					'verif_mlt;', ...
					'recap_phys_mlt;', ...
				'end;', ...	
			  'elseif isempty (pass_ref),', ...
			 	'h = questdlg(''Vous desirez creer un fichier multistation ayant par defaut la pression comme parametre de reference.'',''Message'',''Oui'',''Non'',''Non'');', ...
			 	'if strcmp(h,''Oui''),', ...
					'VALMIN = PMINTOT;', ...
					'VALMAX = PMAXTOT;', ...
					'NB_NIV = ((PMAXTOT-PMINTOT) / XET(27)) + 1;', ...
					'ECHANT_REF = XET(27);', ...
					'verif_mlt;', ...
					'recap_phys_mlt;', ...
				'end;', ...
			 'elseif isempty (pass_par),', ...
				'h = questdlg(''Vous desirez creer un fichier multistation ayant par defaut tous les parametres physiques existant dans les fichiers unistation que vous avez choisis.'',''Message'',''Oui'',''Non'',''Non'');', ...
				'if strcmp(h,''Oui''),', ...
					'CODES_PARAMP_CHOISI = CODPARP_TOT;', ...
					'recap_phys_mlt;', ...
				'end;', ...
			 'else,recap_phys_mlt ; end']); 


% sous-menu qui permet a l'utilisateur de choisir le format de son fichier multistation
% *************************************************************************************

h_supp = uimenu(h5,'Label','Creation ...', ...
                'Separator','on') ;
	       

% sous-menu qui permet a l'utilisateur de creer directement son fichier multistation
% en choisissant le format qu'il veut utiliser 
% mais il ne peut ni verifier ses choix, ni les modifier
% ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


uimenu(h_supp,'Label','Format MATLAB ...', ...
       'Separator','on', ...
       'Callback',['typ_mlt=1;creat_phys_mlt(typ_mlt)';]); 


uimenu(h_supp,'Label','Format NETCDF ...', ...
       'Separator','on', ...
       'Callback',['typ_mlt=2;creat_phys_mlt(typ_mlt);']);



% ==============================================================

% BOUTON QUITTER APPLICATION
% --------------------------

h6=uimenu(f, 'Label', 'Quitter ');


% sous-menu du menu Quitter
% --------------------------

% sous-menu qui permet a l'utilisateur de quitter l'application, de fermer toutes
% les fenetres qui sont restees eventuellement ouvertes et d'effacer toutes les variables.
% ****************************************************************************************

uimenu(h6,'Label','Quitter l''application', ...
          'Callback','clear all,close');


% -----------------------------------------------------------------

% Titre de l'interface
% ---------------------

uicontrol('Parent',f, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',16, ...
	'Position',[0.2 0.50 0.45 0.2], ...
	'String','TRACE DE', ...
	'Style','text');

uicontrol('Parent',f, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',16, ...
	'Position',[0.2 0.20 0.45 0.2], ...
	'String','SECTIONs', ...
	'Style','text');


% Zone du logo
% ------------
	
axes('position',[0.75 0.1 0.2 0.8]);

% Logo
% ----

[x map]=imread('lpo.jpg');
image(x);
colormap(map);
axis off;

clear current;
