%-----------------------------------------------------------------------------------
%  Projet ATLANTIQUE
%  -----------------
%  Version: 1.0
%  ------------
%  Creation : Octobre 2001 /  C.Grit
%  Modification : Juin 2002
%
% repris par C. Lagadec pour projet Atlantique
%                                            
%-------------------------------------------------------------------------------
%  Plots de controle suivant la demande de l'utilisateur
%-------------------------------------------------------------------------------

parameters;



% initialisations par defaut
%---------------------------

icarte   = 0;
iprofil  = 0;
isection = 0;
param    = [];
indice   = 0;

% initialisation de la table des couleurs
tab_coul = ['b';'g';'r';'v';'m';'y';'k'];

[a,b] = size(param_extract)

% le parametre DEPH est systematiquement selectionne 
param_visu(1:a-1,:) = param_extract(2:a,:);


% ajustement des latitudes  min et max 
%        et des longitudes min et max 
%  aux stations selectionnees

lon_extract_min = min(londeb_sta)-5.;
lon_extract_max = max(londeb_sta)+5.;
lat_extract_min = min(latdeb_sta)-5.;
lat_extract_max = max(latdeb_sta)+5.;


if lat_extract_max > 89.95
           lat_extract_max = 88.95;
end



% on peut tracer la carte de positions des stations  
% ou faire des traces de profils  
% ou des traces de section
%---------------------------------------------------------------

fig_import = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
        'Name','CHOIX DE VISUALISATION', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[0.487 0.376 0.3 0.3], ...
        'NumberTitle','off',...
	'MenuBar','none');
	
% trace de la carte de positions des profils
%--------------------------------------------
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.01 0.7 0.8 0.08], ...
	'String','Carte de positions des stations', ...
	'Style','text');

h1 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
        'Callback',['global icarte;',...
		    'icarte=get(gco,''Value'');'], ...
	'Position',[0.85 0.7 0.08 0.08], ...
	'Style','CheckBox');


% trace de profils 
%------------------
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.01 0.5 0.8 0.08], ...
	'String','Traces Profils', ...
	'Style','text');

h2 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
        'Callback',['global iprofil;',...
		    'iprofil=get(gco,''Value'');'], ...
	'Position',[0.85 0.5 0.08 0.08], ...
	'Style','CheckBox');

% trace de section 
%------------------
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.01 0.3 0.8 0.08], ...
	'String','Traces Sections', ...
	'Style','text');

h1 = uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
        'Callback',['global isection;',...
		    'isectionl=get(gco,''Value'');'], ...
	'Position',[0.85 0.3 0.08 0.08], ...
	'Style','CheckBox');

% push ok
%---------
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.4 0.06 0.2 0.1], ...
        'Callback',['global icarte iprofil isection;',...
	'if isempty(icarte),',...
	'    icarte=0;',...
	'end;',...
	'if isempty(iprofil),',...
	'    iprofil=0;',...
	'end;',...
        'if isempty(isection),',...
	'    isection=0;',...
	'end;',...
	'close;'],...
	'String','OK',...
	'Style','Pushbutton');

% push annuler
%-------------
uicontrol('Parent',fig_import, ...
	'Units','normalized', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.6 0.06 0.2 0.1], ...
        'Callback','close', ...
	'String','Annuler');
	
uiwait(fig_import);


%=============================================
% Trace de la carte des positions des stations
%=============================================

if (icarte==1) 
     figure;
     m_proj('mercator','lon',[lon_extract_min lon_extract_max],'lat',[lat_extract_min lat_extract_max]);
     hold on;
%     m_coast('linewidth',2,'color',[1 0 0]);
%    m_coast('patch',[0.60  0.50  0.40],'edgecolor','none');
     m_gshhs_i('patch',[0.60  0.50  0.40],'edgecolor','none');
     m_grid('box','fancy','color',[0 0 0],'linestyle','-.');
     [x,y]=m_ll2xy(londeb_sta,latdeb_sta);

     plot(x,y,'r.');

     xlabel('LONGITUDE');
     ylabel('LATITUDE');

%     print ('-djpeg99' ,'visu_positions.jpg')

end; % end du icarte=1

% ===============================================================


%============================
% Trace des profils souhaites 
%============================

if (iprofil==1) 

% choix pour le trace des profils

fig_import2 = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
        'Name','TRACE DES PROFILS', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[0.487 0.376 0.3 0.3], ...
        'NumberTitle','off',...
	'MenuBar','none');


uicontrol('Parent',fig_import2, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.01 0.6 0.5 0.08], ...
	'String','Parametres a tracer', ...
	'Style','text');

h3 = uicontrol('Parent',fig_import2, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
        'Callback',['global param param_visu;',...
		    'i=get(gco,''Value'');',...
		    'param = param_visu(i,:);'],...
	'Position',[0.6 0.6 0.2 0.1], ...
	'Style','popupmenu',...
	'String',param_visu);

uicontrol('Parent',fig_import2, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'ListboxTop',0, ...
	'Position',[0.01 0.4 0.5 0.08], ...
	'String','Indice station (0 si tout)', ...
	'Style','text');

h1 = uicontrol('Parent',fig_import2, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'ListboxTop',0, ...
        'Callback',['global indice;',...
		    'indice=str2num(get(gco,''String''));'],...
	'Position',[0.6 0.4 0.2 0.1], ...
	'Style','edit');

% push ok
%---------
uicontrol('Parent',fig_import2, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.4 0.06 0.2 0.1], ...
        'Callback',['global indice param nb_stat_extract;',...
	'if isempty(param),',...
	    'hh=warndlg(''Parametre a tracer non defini'',''Attention'');',...
	    'waitfor(hh);',...
	    'elseif isempty(indice),',...
	    'hh=warndlg(''Donnez un numero d ordre de station'',''Attention'');',...
	    'waitfor(hh);',...
	    'elseif (indice > nb_stat_extract),',...
	    'hh=warndlg(''Numero d ordre de station inexistant'',''Attention'');',...
	    'waitfor(hh);',...
	  'else,',...
	    'close;',...
	    'end;'],...
	'String','OK',...
	'Style','Pushbutton');
		    
% push annuler
%--------------
uicontrol('Parent',fig_import2, ...
	'Units','normalized', ...
	'FontSize',10, ...
	'ListboxTop',0, ...
	'Position',[0.6 0.06 0.2 0.1], ...
        'Callback','close', ...
	'String','Annuler');
	
uiwait(fig_import2);

% fin choix trace
%-----------------

if (indice == 0) 

% tous les profils a tracer 

   ii = 1;
   jj = 1;
   camp = camp_sta(1,:);
 
%  while camp == camp_sta(ii,:)
%      icamp(jj,:) = 1
%      ii = ii + 1
%   end;

   if strcmp(param,'BRV2') % trace de la frequence de Brunt-Vaisala

	figure;
	ax1=gca;
	set(ax1,'XColor','r','YColor','k');
	hl1=line(brv2_global,-DEPH_sta,'Color','r',...
	    'LineStyle','+','LineWidth',0.0000005);
	hold on;
	legend('N²',4);
        ax2=axes('Position',get(ax1,'Position'),...
	         'XAxisLocation','top',...                               
	         'YAxisLocation','right',...                             
	         'Color','none',...                                      
	         'XColor','b','YColor','k');  
	ylabel(' immersion');
	set(gca,'ylim',[-2000,0]);
	set(gca,'YTick',[-2000:200:0]);
	hl2=line(SIG0_sta,-DEPH_sta,'Color','b',...
	'LineStyle','+','Parent',ax2,'LineWidth',0.0000005);
	grid;
	legend('si0',1);
	titre=['Profils N² et Sigma'];
	title(titre,'FontSize',10);

     else


	figure;
        par_trac = eval([param '_sta']);
        plot(par_trac, -DEPH_sta);
	grid;
	ylabel('Immersion');
	titre=['Profils ' param ' retenus '];
	title(titre,'FontSize',11);

    end;	



% =======================================================================

	
   else 

% un profil precis a tracer 

   k = indice;
 
   if strcmp(param, 'BRV2') 
% trace de la frequence de Brunt-Vaisala----
	   figure;
 	   hl1=line(BRV2_sta(:,k),-DEPH_sta(:,k),'Color','r','LineStyle','+','LineWidth',0.0000005);
	   ax1=gca;
	   set(ax1,'XColor','r','YColor','k');
	   ylabel(' immersion');
%	   set(gca,'ylim',[-2000,0]);
%	   set(gca,'YTick',[-2000:200:0]);
	   ax2=axes('Position',get(ax1,'Position'),...
	   'XAxisLocation','top',...                               
	   'YAxisLocation','right',...                             
	   'Color','none',...                                      
	   'XColor','b','YColor','k');  
	   hl2=line(SIG0_sta(:,k),-DEPH_sta(:,k),'Color','b',...
	   'LineStyle','+','Parent',ax2,'LineWidth',0.0000005);
	   grid;
	   legend('N²','si0',1);
	   titre=['Profils N² et Sigma'];
	   title(titre,'FontSize',10);
	   titre=['Profils N² et Sigma potentielle no : ',num2str(indice) ];
	   title(titre,'FontSize',10);

   else

	    figure;
            par_trac = eval([param '_sta'])
            plot(par_trac(:,k), -DEPH_sta(:,k))
	    grid;
	    ylabel('Immersion');
	    titre=['Profils ' param 'retenus '];
	    title(titre,'FontSize',11);	

	end; % fin des parametres

  end; % fin indice

	
end; %end du if iprofil=1
