function glb_putres(iv,reslat,reslon,resres,resunc,p_resbox,...
p_resfontsize,gmtname,figmt,resboxscale,resboxwidth,...
cposres,cnulres,cnegres,boxname,gilsup,gilinf,p_putgamma,mapproj)
% KEY: Put the residuals on a plot generated ny glb_transmap
% USAGE :
% 
%
%
%
% DESCRIPTION : 
%
%
% INPUT: 
%
%
% OUTPUT:
%
% AUTHOR : A.Ganachaud (ganacho@gulf.mit.edu) , Apr99
%
% SIDE EFFECTS :
%
% SEE ALSO :
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CALLER: glb_transmap
% CALLEE:
	for ir=1:length(reslon)
	  if isnan(resres(ir)) | resres(ir)==0
	    rescolor=cnulres;
	    razi=0;
	  elseif resres(ir)>0
	    rescolor=cposres;
	    razi=0;
	  elseif resres(ir)<0
	    rescolor=cnegres;
	    razi=180;
	  end
	  if ~p_resbox
	    if ~isnan(resres(ir))
	      fprintf(figmt,['pstext %s -R -G%s -Wo -K -O -:'...
		  '<<END >> $outfile\n'...
		  '%4.2g %4.2g %i 0 1 5 %3.2g@+@!+_@+%3.2g\nEND\n'],...
		mapproj,rescolor,...
		reslat(ir),reslon(ir),p_resfontsize,resres(ir),resunc(ir));
	    else	    
	      fprintf(figmt,['pstext %s -R -Wo -G%s -K -O -:'...
		  '<<END >> $outfile\n'...
		  '%4.2g %4.2g %i 0 1 5 @+@!+_@+%3.2g\nEND\n'],...
		mapproj,rescolor,...
		reslat(ir),reslon(ir),p_resfontsize,resunc(ir));
	    end
	  else 
	    %PUT RESIDUALS AS BOXES
	    fres=sprintf('Trans/%s_%s_%i.res',gmtname,boxname,ir);
	    fires=fopen(fres,'w');
	    fprintf(fires,'%8.3f %8.3f %8.3f %8.3f', reslat(ir),...
	      reslon(ir),razi,abs(resres(ir))/resboxscale(iv));
	    fclose(fires);
	    fprintf(figmt,['psxy %s -R %s -Sv%3g/0.001/0.001 ' ...
		'-G%s -K -O -: >>$outfile\n'],fres,mapproj,...
	      resboxwidth,rescolor);
	    
	    %UNCERTAINTY
	    fdres=sprintf('Trans/%s_%s_%i.dres',gmtname,boxname,ir);
	    fidres=fopen(fdres,'w');
	    if 0 %put with error bar behind the box
	      fprintf(fidres,'%8.3f %8.3f %8.3f %8.3f', reslat(ir),...
		reslon(ir),rem(razi-180,360),resunc(ir)/resboxscale(iv));
	      fclose(fidres);
	      fprintf(figmt,['psxy %s -R %s -Sv%3g/0.001/0.001 ' ...
		  '-G%s -K -O -: >>$outfile\n'],fdres,mapproj,...
		resboxwidth,'255/255/255');
	      fprintf(figmt,['psxy %s -R %s -Sv%3g/0.001/0.001 ' ...
		  '-K -O -: >>$outfile\n'],fdres,mapproj,resboxwidth);
	    else
	      fprintf(fidres,'%8.3f %8.3f %8.3f %8.3f\n', reslat(ir),...
		reslon(ir),razi,resunc(ir)/resboxscale(iv));
	      %fprintf(fidres,'%8.3f %8.3f %8.3f %8.3f', reslat(ir),...
	      %	reslon(ir),rem(razi-180,360),resunc(ir)/resboxscale(iv));
	      fclose(fidres);
	      fprintf(figmt,['psxy %s -R %s -Sv%3g/0.001/0.001 ' ...
		  '-G%s -K -O -: >>$outfile\n'],fdres,mapproj,resboxwidth/3,...
		'255/255/255');
	      fprintf(figmt,['psxy %s -R %s -Sv%3g/0.001/0.001 ' ...
		  ' -K -O -: >>$outfile\n'],fdres,mapproj,resboxwidth/3);
	      if p_putgamma %put gamma interfaces
		reslatshift=.9;
		reslonshift=1;
		if resres(ir) > 0
		  if gilsup(ir) ~= 0 & gilsup(ir) ~= 22 & ...
		      ((ir>1)&(gilsup(ir)~=gilinf(ir-1)))
		    fprintf(figmt,['pstext %s -R -G%s -K -O -:'...
			'<<END >> $outfile\n'...
			'%4.2g %4.2g %i 0 1 RM %3.4g\nEND\n'],mapproj,'0/0/0',...
		      reslat(ir)+reslatshift,reslon(ir)-reslonshift,8,gilsup(ir));
		  end
		  if gilinf(ir)~=48 & gilinf(ir)~=100  & gilinf(ir)~=99
		    fprintf(figmt,['pstext %s -R -G%s -K -O -:'...
			'<<END >> $outfile\n'...
			'%4.2g %4.2g %i 0 1 RM %3.4g\nEND\n'],mapproj,'0/0/0',...
		      reslat(ir)-reslatshift,reslon(ir)-reslonshift,8,gilinf(ir));
		  end
		else
		  if gilsup(ir) ~= 0 & gilsup(ir) ~= 22 &...
		      ((ir>1)&(gilsup(ir)~=gilinf(ir-1)))
		    fprintf(figmt,['pstext %s -R -G%s -K -O -:'...
			'<<END >> $outfile\n'...
			'%4.2g %4.2g %i 0 1 LM %3.4g\nEND\n'],mapproj,'0/0/0',...
		      reslat(ir)+reslatshift,reslon(ir)+reslonshift,8,gilsup(ir));
		  end
		  if gilinf(ir)~=48 & gilinf(ir)~=100  & gilinf(ir)~=99
		    fprintf(figmt,['pstext %s -R -G%s -K -O -:'...
			'<<END >> $outfile\n'...
			'%4.2g %4.2g %i 0 1 LM %3.4g\nEND\n'],mapproj,'0/0/0',...
		      reslat(ir)-reslatshift,reslon(ir)+reslonshift,8,gilinf(ir));
		  end
		end %if fdres
	      end %if p_putgamma
	    end %if 0
	    %ADD LITTLE AXIS ON RESIDUAL BOXES
	    fprintf(figmt,['psxy %s -R -K -O -:'...
		'<<END >> $outfile\n'...
		'%4g %4g\n%4g %4g\n%4g %4g\n%4g %4g\nEND\n'],...
	      mapproj,reslat(ir)-3,reslon(ir),reslat(ir)-3,reslon(ir),...
	      reslat(ir)+3,reslon(ir),reslat(ir)+3,reslon(ir));
	  end %if ~p_resbox
	end %for ir=1:length(reslon)
