function Creat_ASCI()

globalVarEtiquni;
globalajo;

global CHOIX;

global h_PP ;
global h_PPC;
global h_PC ;
global h_PCC ;
global h_ListLabP;
global h_ListLabC;



if isempty(CHOIX.pmaxtot)
	CHOIX.pmaxtot = PMAXTOT;
end;

if isempty(CHOIX.pmintot)
	CHOIX.pmintot = PMINTOT;
end;

if isempty(CHOIX.echant)
	CHOIX.echant = 1;
end;

l= length(NOM_FILES(1,:));
CHOIX.typfic = NOM_FILES(1,l-5 : l);

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Units','points', ...
	'MenuBar','none', ...
	'Name','Choix des parametres physiques et chimiques', ...
	'NumberTitle','off',...
	'Position',[270 160 450 460]);


% zone texte " Les parametres physiques"
%----------------------------------------
 uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[215.2 424 130 32], ...
	'String','Parametres physiques', ...
	'Style','text');

if (NPARP_TOT > 0)
	
	for i=1:NPARP_TOT
		lig1pp = sprintf('%1c%s%s%s', PRESENCP_TOT (i),CODPARP_TOT (i, :));
		if (i == 1)
			ligpp = lig1pp;
		else
			ligpp = strvcat(ligpp, lig1pp);
		end
	end
end

% listBox des codes des parametres Physiques
% --------------------------------------------------------

 h_PP = uicontrol('Parent',h0, ...
	'Units','points', ...
	'FontSize',12, ...
	'BackgroundColor',[1 1 1], ...
	'CallBack','selectparam(1);', ...
	'Position',[50 301 200 120], ...
	'String',ligpp, ...
	'Style','listbox', ...
	'Value',1);

% zone texte "disponibles"(phys.)
%---------------------------

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[138 423 73 18.4], ...
	'String','Disponibles', ... 
        'FontSize',12, ...
	'Style','text');

% zone de texte "choisi"(phys.)
%--------------------------

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[345 423  68.8 22], ...
	'String','Choisis', ...
        'FontSize',12, ...
	'Style','text');


% zone de texte "choisis"(chim.)
%---------------------------

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[345 247 68.8 22], ...
	'String','Choisis', ...
        'FontSize',12, ...
	'Style','text');

% zone de texte "disponible"(chim.)
%----------------------------

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ... 
        'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[120 247 73 18.4], ...
	'String','Disponibles', ...
	'Style','text');

% zone de texte "Les parametres chimiques"
%-----------------------------------------

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
        'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[224 260 130 33.6], ...
	'String','Parametres chimiques', ...
	'Style','text');

if (NPARC_TOT > 0)
	
	for i=1:NPARC_TOT
		lig1pc = sprintf('%1c%s', PRESENCC_TOT (i), CODPARC_TOT (i, :));
		if (i == 1)
			ligpc = lig1pc;
		else
			ligpc = strvcat(ligpc, lig1pc);
		end
	end


% listBox des codes des parametres Chimiques
% --------------------------------------------------------

 h_PC = uicontrol('Parent',h0, ...
	'Units','points', ...
	'FontSize',12, ...
	'BackgroundColor',[1 1 1], ...
	'CallBack','selectparam(2);', ...
	'Position',[50 80 200 166], ...
	'String',ligpc, ...
	'Style','listbox', ...
	'Value',1);

% listBox des codes des parametres Chimiques Choisis
% ---------------------------------------------------

h_PCC =  uicontrol('Parent',h0, ...
	'Units','points', ...
	'FontSize',12, ...
	'BackgroundColor',[1 1 1], ...
	'CallBack','de_selectparam(2);', ...
	'Position',[345 80 95 166], ...
	'String', CHOIX.codc, ...
	'Style','listbox', ...
	'Value',1);
end

% Bouton Ok
% ---------

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
        'FontSize',12, ...
	'Callback',['if CHOIX.nbparp==0 & CHOIX.nbparc==0,', ...'
                   'h=warndlg(''Vous devez selectionner au moins un parametre.'',''Erreur'');', ...
                 'elseif CHOIX.nbparp>0 & CHOIX.nbparc>0,', ...'
                   'h=warndlg(''Impossible de sélectionner param chim. ET phys.'',''Erreur'');', ...  
                      'else,formatParChoisi,close,end;'], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[70 25 90 30], ...
	'String','OK');


uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback',['close;', ...
                'CHOIX.nbparp=0;  CHOIX.nbparc=0; ,', ...
	            'CHOIX.codp=''; CHOIX.codc=''; '], ... 
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[190 25 90 30], ...
	'String','Annuler');


uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','aide(8)', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[310 25 90 30], ...
	'String','Aide');

% listBox des codes des parametres Physiques Choisis
% ---------------------------------------------------

h_PPC =  uicontrol('Parent',h0, ...
	'Units','points', ...
	'FontSize',12, ...
	'BackgroundColor',[1 1 1], ...
	'CallBack','de_selectparam(1);', ...
	'Position',[348 303 95 115], ...
	'String', CHOIX.codp, ...
	'Style','listbox', ...
	'Value',1);



if nargout > 0, fig = h0; end
