

clear all;
close all;

globalVarEtiquni;

global CHOIX;

globalVarDef;

globalRepDef;

messerr     = 'Vous devez d''abord choisir les fichiers a traiter.';
messerrstat = 'Vous devez d''abord choisir des stations.';
messpo      = 'Vous devez d''abord choisir des parametres.'; 
messparam   = 'Impossible de selectionner des param. physiques ET chimiques';
messechant  = 'Pas echantillonnage possible pour param. chimiques';

init_cre;

CHOIX.pmintot = [];
CHOIX.pmaxtot = [];
CHOIX.echant  = [];
CHOIX.nbparp  = 0;
CHOIX.nbparc  = 0;
CHOIX.codp    = '';
CHOIX.codc    = '';
CHOIX.name    = '';
CHOIX.units   = '';
CHOIX.format = '';





f= figure ('Units','normalized', ...
           'Color',[0.8 0.8 0.8], ...
           'Name','CREASC', ...
           'NumberTitle','off', ...
	   'Position',[0.45 0.81 0.54 0.12], ...
           'MenuBar','none');

% ----------------------------------------------------------


% CONFIGURATION
% =============

h1=uimenu(f,'Label','Configuration   ');

 uimenu(h1,'Label','Environnement de travail ...',...
                'Separator', 'off', ...
                'Callback','choix_envir_cli');

% ----------------------------------------

% STATIONS
% --------

h2 = uimenu(f,'Label','Stations   ');

% sous menus du menu stations 
% ---------------------------

 uimenu(h2,'Label','Suite continue ...', ...
                'Separator','off', ...
                'Callback','stat_suit_asc');

 uimenu(h2,'Label','Catalogue ...', ...
                'Separator','on', ...
                'Callback',['global masq_cat;', ...
                            'masq_cat = ''*.cat'';', ...
                            'stat_cat(masq_cat)']);
uimenu(h2,'Label','Repertoire ...', ...
                'Separator','on', ...
                'Callback',' suf=''.nc'';stat_rep');


 
% --------------------------------------------------


% PARAMETRES
% ==========

h3 = uimenu (f,'Label','Parametres   '); 
 
uimenu(h3,'Label','Parametres ...', ...
    	  'CallBack',['if (isempty(NBFILES)),',  ...
		                  'h=warndlg(messerrstat,''Attention'');', ...
                          'waitfor(h),', ...
	                  'else, Creat_ASCI;', ...
                      '    if (CHOIX.nbparp>0) & (CHOIX.nbparc>0),', ...
	                               'h=warndlg(messparam,''Attention'');', ... 
                                   'waitfor(h),end;end']);

% -------------------------------------------------


% PRECISIONS (formats et echantillonnage)
% ==========

h4 = uimenu(f,'Label','Precisions   ');

uimenu(h4,'Label','Formats ...', ...
		'CallBack',['if (isempty(NBFILES)),', ...
		                 'h=warndlg(messerrstat,''Attention'');', ...
                         'waitfor(h),', ...
                     'elseif (isempty(CHOIX.nbparp)) & (isempty(CHOIX.nbparc)),', ...
	                               'h=warndlg(messpo,''Attention'');', ... 
                                   'waitfor(h),', ...
	                  'else,', ...
                          'modif_param_format;end']);


 uimenu(h4,'Label','Echantillonnage ...', ...
	'CallBack',['if (isempty(NBFILES)),', ...
		               'h=warndlg(messerrstat,''Attention'');', ...
                       'waitfor(h),', ...
	            'elseif (CHOIX.nbparc > 0),', ...
                        'h=warndlg(messechant,''Attention'');', ...
                        'else,', ...
                        'prof_echant; end']);


% -------------------------------------------------------

% CREATION FICHIERS
% =================

h5 = uimenu(f,'Label','Creation des Fichiers   ');

uimenu(h5,'Label','Recapitulatif ...', ...
          'Callback',['if (isempty(NBFILES)),', ...
		                 'h=warndlg(messerrstat ,''Attention'');', ...
                         'waitfor(h),', ...
		              'else, recupStations;VosChoix; end']);


uimenu(h5,'Label','Creation des fichiers Echange ...', ...
          'Callback',['if (isempty(NBFILES)),', ...
		'warndlg(messerrstat ,''Attention'');', ...
		'else, recupStations;', ...
              'option =''unique'';creat_asci_standard(option);end']);

uimenu(h5,'Label','Creation des fichiers separes ...', ...
          'Callback',['if (isempty(NBFILES)),', ...
                         'warndlg(messerrstat ,''Attention'');', ...
	           	'else,', ...
              'recupStations;', ...
              'option = ''double'';creat_asci_standard(option);end']);


 
% ---------------------------------------------------------

% bouton Quitter application
% --------------------------

h6 = uimenu(f, 'Label', 'Quitter',...
        'Callback',' clear all,  close all');



% Titre de l'interface
% ---------------------
uicontrol('Parent',f, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',16, ...
	'Position',[0.2 0.50 0.45 0.2], ...
	'String','CREATION  DE', ...
	'Style','text');
uicontrol('Parent',f, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',16, ...
	'Position',[0.2 0.20 0.45 0.2], ...
	'String','FICHIERS  ASCI', ...
	'Style','text');


% Zone du logo
% ------------
	
axes('position',[0.75 0.1 0.2 0.8]);

% Logo
% ----

[x map]=imread('lpo.jpg');
image(x);
colormap(map);
axis off;



clear current;
