function fig = modif_param_format()

globalVarEtiquni;

global COD;
global CHOIX;

global h_FormatsAModifier;
global h_ListFormats;
global h_ListUnites;
global h_ListParam;
global valc;

h0 = figure('Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'Name','Modification des formats', ...
	'NumberTitle','off', ...
	'Position',[125 125 725 547]);

h_ListUnites = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[196 115.2 136.8 216.8], ...
	'String',CHOIX.units, ...
        'FontSize',12, ...
	'Style','listbox', ...
        'Enable','inactive', ...
	'Value',1);

h_ListParam = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[56 114.8 80 217.6], ...
	'CallBack',['global h_formatsAModifier;', ...
	' selectformat;'],...
        'FontSize',12, ...
	'String',CHOIX.cod, ...
	'Style','listbox', ...
	'Tag','Listbox2', ...
	'Value',1);

h_ListFormats = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[381.6 114.8 64.8 217.6], ...
	'String', CHOIX.format, ...
	'Style','listbox', ...
        'FontSize',12, ...
        'Enable','inactive', ...
	'Tag','Listbox2', ...
	'Value',1);

h_Txt1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'FontWeight','demi', ...
	'ListboxTop',0, ...
	'Position',[199.2 361.2 131.2 23.2], ...
	'String','Unites', ...
	'Style','text');

h_Txt2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'FontWeight','demi', ...
	'ListboxTop',0, ...
	'Position',[27.2 353.6 131.2 38.4], ...
	'String','Codes des parametres', ...
	'Style','text');

h_Txt3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'FontWeight','demi', ...
	'ListboxTop',0, ...
	'Position',[356.8 361.2 131.2 23.2], ...
	'String','Formats', ...
	'Style','text');

h_BtOK = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'CallBack','close', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[41.6 40.8 110.2 25.6], ...
	'String','OK');

h_BtAnnuler = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'CallBack','close', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[200 39.2 123.2 27.2], ...
	'String','Annuler');

h_BtAide = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','aide(12)', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[351.2 39.2 123.2 27.2], ...
	'String','Aide');

h_FormatsAModifier = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'FontSize',13, ...
	'Position',[469.6 220 68 24], ...
	'String','', ...
	'Style','edit');

h_BtModifier = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'CallBack','modifformat', ...
	'ListboxTop',0, ...
	'Position',[464.8 184 81.6 24], ...
	'String','Modifier', ...
	'FontSize',14);


if nargout > 0, fig = h0; end
