function prof_echant()

globalVarEtiquni;
global COD CHOIX;
globalVarDef;

global h_ProfMin;
global h_ProfMax;
global h_PasEchant;

if isempty(CHOIX.echant)
	CHOIX.echant = 1;
end
if isempty(CHOIX.pmintot)
	CHOIX.pmintot = PMINTOT;
end
if isempty(CHOIX.pmaxtot)
	CHOIX.pmaxtot = PMAXTOT;
end;

h0 = figure('Color',[0.8 0.8 0.8], ...
	'Name','Echantillonnage', ...
	'NumberTitle','off', ...
	'Position',[300 300 426 415], ...
        'MenuBar','none');



h_ProfMin = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
        'FontSize', 12, ...
	'ListboxTop',0, ...
	'Position',[184 190.4 80.8 24.8], ...
	'String', PMINTOT, ...
	'Style','edit');


h_ProfMax = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
        'FontSize', 12, ...
	'ListboxTop',0, ...
	'Position',[184 144 80.8 24.8], ...
	'String', PMAXTOT, ...
	'Style','edit');


uicontrol('Parent',h0, ...
	'Units','points', ...
	'FontWeight','bold', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[23.2 190.4 113.6 23.2], ...
	'String','Pression minimale', ...
        'FontSize', 12, ...
	'Style','text');


uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontWeight','bold', ...
        'FontSize', 12, ...
	'Position',[23.2 144 113.6 23.2], ...
	'String','Pression maximale', ...
	'Style','text');



h_BtOK = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'CallBack','selectechant', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'Position',[12.8 28.8 83.2 24.8], ...
	'String','OK');

h_BtAnnuler = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','close', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'Position',[115.2 28.8 82.4 24.8], ...
	'String','Annuler');

h_BtAide = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','aide(11)', ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'Position',[220 29.6 80 24], ...
	'String','Aide');

h_PasEchant = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[184 97.6 80.8 24.8], ...
	'String',CHOIX.echant, ...
        'FontSize', 12, ...
	'Style','edit');

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
        'FontSize', 12, ...
	'FontWeight','bold', ...
	'Position',[22.4 96 113.6 23.2], ...
	'String','Pas d''echantillonnage', ...
	'Style','text');

if nargout > 0, fig = h0; end
