function stat_suit_asc ()

%---------------------------------------------------------------
% Saisie des elements pour le traitement d'une suite de fichiers
% C.B. 21/04/97
%---------------------------------------------------------------

globalVarEtiquni;

DIRECTION = 'd';
suf = '_cli.nc';

% Fenetre de saisie pour une suite continue (fig)
a = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Name','Suite continue de stations', ... 
        'NumberTitle','off',...
        'MenuBar','none',...
	'Position',[0.25 0.4 0.5 0.2]);

% Code de la campagne (txt)
uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'HorizontalAlignment','left', ...
	'Position',[0.03 0.58 0.2 0.12], ...
	'String','Code Campagne', ...
	'Style','text');

% Saisie du code de la campagne (edit)
% -> saisie du code campagne dans <code_camp>
% -------------------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'String',IDENTCAMP, ... 
	'Callback','IDENTCAMP=get(gco,''String'');', ...
	'FontSize',12, ...
	'HorizontalAlignment','left', ...
	'Position',[0.23 0.6 0.13 0.12], ...
	'Style','edit');

% Suffixe (txt)
% ------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'HorizontalAlignment','left', ...
	'Position',[0.03 0.38 0.1 0.12], ...
	'String','Suffixe', ...
	'Style','text');

% Choix du suffixe (popup)
% 'bru', 'cli' ou 'clc' 
% -> <suf>
% -----------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback',['s=get(gco,''value'');', ...
                'if s == 2,', ...
                'suf = ''_clc.nc'';end'], ...             
	'FontSize',12, ...
	'HorizontalAlignment','left', ...
	'Position',[0.23 0.4 0.1 0.12], ...
	'String',['cli.nc';'clc.nc'], ...
	'Style','popupmenu', ...
	'Value',1);

% Fichier en descente ou en monte (popup)
% -> <DIRECTION>, A ou D
%------------------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback',['direct=get(gco,''Value'');', ...
                'if direct==2,', ...
                 'DIRECTION = ''a'';end'], ...
	'FontSize',12, ...
	'HorizontalAlignment','left', ...
	'Position',[0.4 0.6 0.17 0.12], ...
	'String',[' Descending';' Ascending '], ...
	'Style','popupmenu', ...
	'Value',1);

% Numero de la premiere station (txt)
% -----------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'HorizontalAlignment','left', ...
	'FontSize',12, ...
	'Position',[0.60 0.58 0.2 0.12], ...
	'String','No 1ere station', ...
	'Style','text');

% Saisie de la premiere station (edit)
% -> <STAT1>
% -----------------------------------


uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','STAT1=str2num(get(gco,''String''));', ...
	'FontSize',12, ...
        'String', STAT1, ...
	'Position',[0.88 0.6 0.1 0.12], ...
	'Style','edit');

% Numero de la derniere station (txt)
% -----------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'HorizontalAlignment','left', ...
	'Position',[0.6 0.38 0.25 0.12], ...
	'String','No derniere station', ...
	'Style','text');

% Saisie de la derniere station (edit)
% -> <STATN>
% ------------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'String', STATN, ...
	'Callback','STATN=str2num(get(gco,''String''));', ...
	'FontSize',12, ...
	'Position',[0.88 0.4 0.1 0.12], ...
	'Style','edit');

% Ok (push)
% -----------------------------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback', ['globalVarEtiquni;', ...
                     'if STATN < STAT1,', ...
                     '  mess = ''Le numero de la derniere station doit etre superieur ou egal a celui de la premiere.'';', ...
                     '  h = warndlg(mess,''Erreur'');', ...
                     '  waitfor(h);', ...
                     ' else,', ...
                     '   mfiles_suit;', ...
                     '   if  isempty(NOM_FILES),', ...
                     '   h=warndlg(''Toutes les zones n''''ont pas ete saisies.'',''Erreur'');', ...
                     'else,', ...
                     '   close;', ...
                     '   existe_files; ', ...
                     '   if NBFILES > 0,', ...
                     '      verif_station;', ...
                     '   end,', ...
                     '   end,', ...
                     'end'], ...
	'FontSize',12, ...
	'Position',[0.03 0.1 0.2 0.15], ...
	'String','OK');


% Annuler (push)
% -----------------------------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback', 'close',  ...
	'FontSize',12, ...
	'Position',[0.5 0.1 0.2 0.15], ...
	'String','Annuler');

clear current;


