function fig = VosChoix()

globalVarEtiquni;
global CHOIX;

if strcmp(DIRECTION,'d')
    direct = 'Descending';
else
    direct = 'Ascending';
end

h0 = figure('Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'Name','Vos Choix', ...
	'NumberTitle','off', ...
	'Position',[100 100 881 710]);


uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
        'FontSize',12, ...
	'Position',[56 40 100 320], ...
	'String', CHOIX.cod, ...
	'Style','listbox', ...
	'Value',1);

uicontrol('Parent',h0, ...
	'Units','points', ...
        'FontSize',12, ...
	'BackgroundColor',[1 1 1], ...
	'Position',[170 40 260 320], ...
	'String',CHOIX.name, ...
	'Style','listbox', ...
	'Value',1);

 uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
        'FontSize',12, ...
	'Position',[56 413 91 30], ...
	'String', CHOIX.pmintot, ...
	'Style','edit', ...
	'Enable','Inactive');

 uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
        'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[215 413 91 30], ...
	'String', CHOIX.pmaxtot, ...	
	'Style','edit', ...
	'Enable','Inactive');

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
        'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[380 413 91 30], ...
	'String', CHOIX.echant , ...
	'Style','edit', ...
	'Enable','Inactive');

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
        'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[520 413 91 30], ...
	'String', CHOIX.typfic , ...
	'Style','edit', ...
	'Enable','Inactive');

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
        'FontSize',12, ...
	'Position',[430 38.4 80 320], ...
	'String', CHOIX.format, ...
	'Style','listbox', ...
	'Value',1);

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[56 360 91 30], ...
	'String','CODES', ...
	'Style','text');

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[215 360 91 30], ...
	'String','LABELS', ...
	'Style','text');

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[380 360 91 30], ...
	'String','FORMATS', ...
	'Style','text');

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[56 440 91 30], ...
	'String','Pression Minimum', ...
	'Style','text');

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[215 440 91 30], ...
	'String','Pression Maximum', ...
	'Style','text');

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[380 440 120 30], ...
	'String','Pas d''echantillonnage', ...
	'Style','text');

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[520 440 120 30], ...
	'String','Type Fichier', ...
	'Style','text');

%-----------------------------------------------%
%le bouton qui permet de lancer l'ecriture des  %
%fichiers ASCI de type .ecp ou .ecc		        %
%-----------------------------------------------%

h_BtASCIStand = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback', ';option =''unique'';creat_asci_standard(option);', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[520 260 160 55], ...
	'String','Fichiers Echange');

% Bouton qui permet de lancer l'ecriture des  
% fichiers ASCI de type .desc et .asc		

h_BtASCI2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback', 'option = ''double'';creat_asci_standard(option);', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[520 180 160 55], ...
	'String','Fichiers Separes');

%----------------------------------------------- %
% Bouton qui permet de relancer completement	 %
% l'application comme si aucun choix n'avait ete %
% fait par l'utilisateur			             %
%------------------------------------------------%

h_BtModifier = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.7 0.7 0.7], ...
	'Callback','close;', ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[520 100 160 55], ...
	'String','Modification des choix/Fin');

% Nom de la campagne choisie	

h_NomCamp = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
        'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[56 497 91 30], ...
	'String',IDENTCAMP, ...
	'Style','edit', ...
	'Enable','Inactive');

% premiere station choisie 

h_PremStat = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
        'FontSize',12, ...
	'Position',[215 497 91 30], ...
	'String',STAT1, ...
	'Style','edit', ...
	'Enable','Inactive');

% derniere station choisie 

h_DernStat = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
        'FontSize',12, ...
	'Position',[380 497 91 30], ...
	'String',STATN, ...
	'Style','edit', ...
	'Enable','Inactive');

% montee ou descente 

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
        'FontSize', 12, ...
	'Position',[520 497 91 30], ...
	'String',direct, ...
	'Style','edit', ...
	'Enable','Inactive');

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[56 527 91 30], ...
	'String','Nom de la Campagne', ...
	'Style','text', ...
	'Enable','Inactive');

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[215 527 91 30], ...
	'String','Premiere station', ...
	'Style','text', ...
	'Enable','Inactive');

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[380 527 91 30], ...
	'String','Derniere station', ...
	'Style','text');


uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[520 527 91 30], ...
	'String','Profils', ...
	'Style','text', ...
	'Enable','Inactive');


if nargout > 0, fig = h0; end
