pgf90 -Mextend  -fast -O4 -c -o glabel_matlab.o glabel_matlab.f
pgf90 glabel_matlab.o ../gamma.a /home/porzig/services/netcdf/netcdf-3.5.0/lib/libnetcdf.a -o glabel_matlab
pgf90 -Mextend -fast -O4 -c -o nsfces_matlab-linux.o nsfces_matlab-linux.f
pgf90 nsfces_matlab-linux.o ../gamma.a /home/porzig/services/netcdf/netcdf-3.5.0/lib/libnetcdf.a -o nsfces_matlab
