function choix_param_phys()

%------------------------------------------------------------------
% 								                                 
% fonction qui permet a  l'utilisateur de choisir les parametres  
% physiques qu'il desire voir apparaitre dans                   
% son fichier multistation. Le cas echeant, tous les parametres 
% sont selectionnes par defaut.                               
%								                                  
%------------------------------------------------------------------


globalVarEtiquni ;
globalajo ;
globalVarASCI ;
globalVMLT ;

global h_CODESPARAMPC ;


% le test qui suit permet de determiner si c'est la premiere fois 
% qu'on vient dans ce menu.
% -----------------------------------------------------------------

if (isempty(NB_PARAMP_CHOISI))
	NB_PARAMP_CHOISI = 0 ;
end ;


% choix des parametres physiques
% ------------------------------

h0 = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'Name','Choix des parametres physiques', ...
	'NumberTitle','off', ...
	'Position',[0.419 0.262 0.537 0.367]);
	
% ------------------------------------------------
% zone de texte choix des "parametres physiques"
% ------------------------------------------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.334 0.918 0.392 0.0515], ...
	'String','Les parametres physiques', ...
	'Style','text') ;
	
% zone de texte parametres physiques "disponibles"
% -----------------------------------------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.1357 0.876 0.1630 0.048], ...
	'String','Disponibles', ...
	'Style','text') ;


% concatenation dans une listbox d'une etoile si le parametre physique
% en question n'est pas present dans tous les fichiers, du code du 
% parametre physique et de son label.
% ---------------------------------------------------------------------

listPP = '' ;
espace = blanks(10) ;

if(ETIQ.nparp > 0)
	for i = 1:ETIQ.nparp
        if   ~strcmp(CODPARP_TOT (i, :),CODE_REF)
		       list1PP = sprintf('%s  %s%s', PRESENCP_TOT(i),CODPARP_TOT (i, :), espace, LABPARP_TOT(i, :)) ;
		       if (i == 1)
			       listPP = list1PP ;
                 else
			       listPP = strvcat(listPP, list1PP) ;
               end            
        end
    end
end


% listbox des codes et des labels des parametres physiques disponibles
% --------------------------------------------------------------------

h_CODLABPARAMP = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'FontSize',12, ...
	'Callback',['globalVarASCI;', ...
		'ierr = select_param_mlt;'], ...
	'Position',[0.0355 0.203 0.454 0.606], ...
	'String', listPP, ...
	'Style','listbox', ...
	'Value',1);


% zone de texte des parametres physiques "choisis"
% -----------------------------------------------

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.69 0.203 0.454 0.606], ...
	'String','Choisis', ...
	'Style','text') ;
	
% listbox des codes des parametres physiques choisis
% --------------------------------------------------

h_CODESPARAMPC = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
	'Callback',['globalVarASCI;', ...
		'deselect_param_mlt;'], ...
	'Position',[0.6381 0.209 0.17 0.588], ...
	'String',CODES_PARAMP_CHOISI, ...
	'Style','listbox', ...
	'Value',1);

% bouton "Ok"
% -----------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7020 0.7020 0.7020], ...
	'Callback','close', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.09 0.066 0.205 0.1], ...
	'String','Ok') ;

% bouton "Annuler"
% ---------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7020 0.7020 0.7020], ...
	'Callback',['close;', ...
		'NB_PARAMP_CHOISI = [] ; ', ...
		'CODES_PARAMP_CHOISI = '' ; ,', ...
        'LABELS_PARAMP_CHOISI = '' ; ,', ...
		'pass_par = [];'], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.357 0.066 0.205 0.1], ...
	'String','Annuler') ;
	
% bouton "Aide"
% ------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7020 0.7020 0.7020], ...
	'Callback','aides(2)', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.63 0.066 0.205 0.1], ...
	'String','Aide') ;

if nargout > 0, fig = h0; end
