
function init_cre_mlt ()

%-------------------------------------------					
% fonction qui permet d'initialiser quelques     
% matrices et quelques variables						
%--------------------------------------------

globalVarEtiquni ;
globalVMLT ;

% initialisation des matrices representant les codes et les labels 
% des parametres de reference autorises
% ------------------------------------------------------------------

CODES_AUT_DEF = ['TPOT';'ZCOO';'DEPH';'IMMR';'SIGI';'SIG0';'SIG1';'SIG2';'SIG3';'SIG4';'SIG5';'SIG6';'SI15'] ;

LABELS_AUT_DEF = ['TEMP.POTENT. '; ...
                  'COORD.Z(neg) '; ...
                  'COORD.Z(pos) '; ...
                  'IMMERSION    '; ...
                  'SIGMA in situ'; ...
                  'SIGMA/0      '; ...
                  'SIGMA/1000   '; ...
                  'SIGMA/2000   '; ...
                  'SIGMA/3000   '; ...
                  'SIGMA/4000   '; ...
                  'SIGMA/5000   '; ...
                  'SIGMA/6000   '; ...
                  'SIGMA/1500   '];

% inialisation du nombre de parametres physiques et chimiques choisis
% --------------------------------------------------------------------

NB_PARAMP_CHOISI = 0 ;
NB_PARAMC_CHOISI = 0 ;
