function nom_fic_mlt

%-------------------------------------------------
%                                                
% fonction qui permet a l'utilisateur de changer 
% le nom du fichier multistation qu'il va creer  
% au lieu de garder celui donne par defaut.      
%                                                
% suffixe = .nc  si fichier Netcdf               
%                                               
%-------------------------------------------------


globalVarEtiquni ;
globalVMLT ;

global nom_fich ;

suffixe = '.nc';

% affichage du nom de fichier multistation par defaut
% ---------------------------------------------------

 nom_fich = NOM_FIC_DEF(1:(length(NOM_FIC_DEF)-3));

% nom du fichier multistation cree a partir de fichiers unistation
% ------------------------------------------------------------------

fig_nom = figure('Units','points', ...
	'Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'Name','Nom du fichier multistation', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[270.4 358.4 214.4 89.60]);

% affichage du nom du fichier multistation par defaut ; il est compose 
% de l'identifiant de la campagne qu'il concerne (et par defaut de la premiere
% choisie, si l'utilisateur en choisit plusieurs), suivi du code du
% parametre de reference choisi par l'utilisateur, 
% suivi du suffixe  ".nc" (fichier Netcdf)
% -----------------------------------------------------------------------------

h1 = uicontrol('Parent',fig_nom, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',('MLT.nomfic = [get(gco,''String'') ''.nc''];'), ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.1903 0.50 0.4590 0.3036], ...
	'String',nom_fich, ...
	'Style','edit');

% zone de texte du suffixe du fichier 
% -----------------------------------

h1 = uicontrol('Parent',fig_nom, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.6604 0.5089 0.1567 0.2589], ...
	'String',suffixe, ...
	'Style','text');

% bouton "Ok"
% -----------

h1 = uicontrol('Parent',fig_nom, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7020 0.7020 0.7020], ...
	'Callback','close', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.2985 0.0893 0.2164 0.3036], ...
	'String','Ok');


uiwait(fig_nom) ;
