function fig = param_ref_choisi()

	%------------------------------------------------------
	%  fenetre qui permet a l'utilisateur de choisir     
	%  un nouveau parametre de reference parmi une liste 
	%  de parametres autorises.                          
	%------------------------------------------------------


globalVarEtiquni ;
globalVMLT ;

global cod pas ;


% parametres de reference autorises
% ----------------------------------

h0 = figure('Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'Name','Changement du parametre de reference', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[63 292 558 497]);

% zone de texte des "parametres autorises"
% -----------------------------------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.10633 0.9287 0.3135 0.0461], ...
	'String','parametres autorises', ...
	'Style','text') ;
	
listPA = [] ;
espace1 = blanks (10) ;

for i = 1:size(CODES_AUT_DEF,1)
	
	list1PA = sprintf('   %s%s%s',CODES_AUT_DEF(i,:)',espace1, LABELS_AUT_DEF(i,:)') ;
	if (i == 1)
		listPA = list1PA ;
	else
		listPA = strvcat(listPA, list1PA) ;
	end ;

end ;


% listbox des codes et des labels des parametres de reference autorises.
% ---------------------------------------------------------------------


h_paramAuto = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Callback',['val = get(gco,''Value'');', ...
	            'paramcod = CODES_AUT_DEF(get(gco,''Value''),:);', ...
                'verif_mlt(paramcod);', ...
	            'set(PAR_AUTO,''String'',paramcod);', ...
                'set(VMIN_AUTO,''String'',VMINTOT);', ...
                'set(VMAX_AUTO,''String'',VMAXTOT);'], ...
	'FontSize',12, ...
	'Position',[0.0376 0.4306 0.9247 0.4728], ...
	'String',listPA, ...
	'Style','listbox', ...
	'Value',1);
	

% zone de texte "code de parametre de reference choisi"
% --------------------------------------------------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.0197 0.3280 0.2778 0.0724], ...
	'String','Code du parametre de reference choisi', ...
	'Style','text') ;
	
% zone edit du code du parametre de reference choisi par l'utilisateur.
% cette zone peut etre modifiee par l'utilisateur, lorsqu'il clique
% sur un des elements de la liste des parametres autorises.
% ---------------------------------------------------------------------

PAR_AUTO = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','paramcod = get(gco,''String'');',...
	'Enable','inactive', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.3441 0.3340 0.1362 0.0543], ...
	'String',cod, ...
	'Style','edit') ;

% zone de texte "valeur min"
% --------------------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.0197 0.2596 0.1416 0.0423], ...
	'String','valeur min', ...
	'Style','text') ;

% zone edit de la valeur minimale du parametre de reference choisi par
% l'utilisateur. Cette zone peut etre modifiee par l'utilisateur.
% ----------------------------------------------------------------------- 

VMIN_AUTO = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',['parammin = str2num(get(gco,''String''));', ...
		    'if parammin < VMINTOT,', ...
			'parammin = VMINTOT;', ...
		    'end;'], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.3441 0.2575 0.1362 0.0543], ...
	'String',VMINTOT, ...
	'Style','edit') ;

% zone de texte "valeur max"
% --------------------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.0197 0.1831 0.1416 0.0423], ...
	'String','valeur max', ...
	'Style','text') ;

% zone edit (modifiable) de la valeur maximale du parametre de reference 
% ----------------------------------------------------------------------

VMAX_AUTO = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',['parammax = str2num(get(gco,''String''));', ...
		    'if parammax > VMAXTOT,', ...
			'parammax = VMAXTOT;', ...
		    'end;'], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.3441 0.1831 0.1362 0.0543], ...
	'String',VMAXTOT, ...
	'Style','edit') ;
	

% zone de texte "Pas d'echantillonnage"
% -------------------------------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.01971 0.0966 0.2652 0.0443], ...
	'String','pas d''echantillonnage', ...
	'Style','text') ;
	
% zone edit (modifiable) du pas d'echantillonnage du parametre de reference 
% -------------------------------------------------------------------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback','ECHANT_AUTO = str2num(get(gco,''String''));', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.3441 0.1046 0.1362 0.0543], ...
	'String',pas, ...
	'Style','edit') ;

% bouton "Ok"
% -----------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7020 0.7020 0.7020], ...
	'Callback',['if (isempty(paramcod)),', ...
			'h = warndlg(''Vous devez choisir un parametre de reference'',''Attention'');', ...
		        'waitfor(h),', ...
		     'elseif (isempty(ECHANT_AUTO)),', ...
			'h = warndlg(''Vous devez saisir le pas d''''echantillonnage du parametre de reference choisi'',''Attention'');', ...
			'waitfor(h),', ...
		     'elseif (~isempty(paramcod) & ~isempty(ECHANT_AUTO)),', ...
             'if isempty(paramcod),', ...
			    'CODE_REF = cod;', ...
                  'else,', ...
			    'CODE_REF = paramcod ;', ...
             'end;', ...
             'if isempty(parammin),', ...
			    'VALMIN = VMINTOT;', ...
                  'else,', ...
			    'VALMIN = parammin ;', ...
             'end;', ...
             'if isempty(parammax),', ...
			    'VALMAX = VMAXTOT;', ...
                  'else,', ...
			    'VALMAX = parammax ;', ...
             'end;', ...
                'if isempty(ECHANT_AUTO),', ...
			    'ECHANT_REF = pas;', ...
                  'else,', ...
			    'ECHANT_REF = ECHANT_AUTO;', ...
                'end,', ...
			 'set(h_CODE,''String'',CODE_REF);', ...
			 'set(h_VMIN,''String'',VALMIN);', ...
			 'set(h_VMAX,''String'',VALMAX);', ...
			 'set(h_ECHANT,''String'',ECHANT_REF);', ...
			 'close;', ...
		     'end;'], ...		     
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.6703 0.2837 0.2330 0.0946], ...
	'String','Ok') ;


% bouton "Annuler"
% ----------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7020 0.7020 0.7020], ...
	'Callback','close', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.6703 0.1670 0.2330 0.0946], ...
	'String','Annuler') ;
	
% bouton "Aide"
% --------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7020 0.7020 0.7020], ...
	'Callback','aides(3)', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.6703 0.0463 0.2330 0.0946], ...
	'String','Aide') ;
	
if nargout > 0, fig = h0; end
