function param_ref_mlt()

%---------------------------------------------------------------------
%  fenetre qui indique le parametre de reference existant, a savoir   
%  la pression, la Valeur minimale, la Valeur maximale et le pas      
%  d'echantillonnage de cette pression, et qui donne la possibilite a 
%  l'utilisateur de modifier ce parametre de reference.               
%----------------------------------------------------------------------


globalVarEtiquni ;
globalVarASCI ;
globalVMLT ;

% variables intermediaires
% -------------------------

global vmin vmax echant code ;


% tests pour verifier si l'utilisateur saisit ou pas de nouvelles Valeurs
% (Valeur min, Valeur max, pas d'echantillonage, et code) concernant
% le parametre de reference
% ------------------------------------------------------------------------

if isempty(VALMIN)
	vmin = PMINTOT ;
else
	vmin = VALMIN ;
end ;

if isempty(VALMAX)
	vmax = PMAXTOT ;
else
	vmax = VALMAX ;
end ;

if isempty(ECHANT_REF)
	echant = ETIQ.interv ;
else
	echant = ECHANT_REF ;
end ;

if isempty(CODE_REF)
	code = 'PRES' ;
else
	code = CODE_REF ;
end;



% parametre de reference
% ----------------------

h0 = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'Name','Parametre de reference', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[0.4514 0.3133 0.4375 0.4102]);

% ------------------------
% zone de texte "existant"
% ------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.1571 0.9071 0.2607 0.05], ...
	'String','EXISTANT', ...
	'Style','text') ;

% zone de texte "code du parametre de reference"
% ----------------------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.05 0.772 0.268 0.084], ...
	'String','Code du parametre de reference', ...
	'Style','text') ;
	
% zone edit du code du parametre de reference
% --------------------------------------------

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Enable','inactive', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[150.4 248.8 58.4000 23.2], ...
	'String','PRES', ...
	'Style','edit') ;

% zone de texte "Valeur min"
% ---------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.055 0.712 0.1964 0.0461], ...
	'String','Valeur min', ...
	'Style','text') ;
	
% zone edit de la Valeur min
% --------------------------

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Enable','inactive', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[150.4 216.8 58.4000 23.2], ...
	'String',PMINTOT, ...
	'Style','edit') ;

% zone de texte "Valeur max"
% --------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.0615 0.6125 0.175 0.0429], ...
	'String','Valeur max', ...
	'Style','text') ;

% zone edit de la Valeur max
% ---------------------------

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Enable','inactive', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[150.4 187.2 58.4000 23.2], ...
	'String',PMAXTOT, ...
	'Style','edit') ;

% zone de texte "pas d'echantillonnage"
% --------------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.047 0.5014 0.2857 0.05], ...
	'String','Pas d''echantillonnage', ...
	'Style','text') ;

% zone edit du Pas d'echantillonnage
% ----------------------------------

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Enable','inactive', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[150.4 153.6 58.4000 23.2], ...
	'String',ETIQ.interv, ...
	'Style','edit') ;

% --------------------
% zone de texte "mlt"
% --------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.5732 0.9095 0.2893 0.05], ...
	'String','MLT', ...
	'Style','text') ;

% zone de texte "code du parametre de reference"
% ----------------------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.5437 0.789 0.2679 0.0833], ...
	'String','Code du parametre de reference', ...
	'Style','text') ;

% zone edit du code du parametre de reference
% -------------------------------------------

h_CODE = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',['CODE_REF = get(gco,''String'');'], ...
	'Enable','inactive', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[368.8 256 58.4000 23.2], ...
	'String',code, ...
	'Style','edit') ;

% zone de texte "Valeur min"
% --------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.552 0.707 0.2 0.0462], ...
	'String','Valeur min', ...
	'Style','text') ;

% zone edit de la Valeur min
% ---------------------------

h_VMIN = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',['global vmin;', ...
		    'VALMIN = str2num(get(gco,''String''));', ...
		    'if VALMIN < vmin,', ...
			'VALMIN = vmin;', ...
		    'end;'], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[369.6 218.4 58.4000 23.2], ...
	'String',vmin, ...
	'Style','edit') ;
	
% zone de texte "Valeur max"
% --------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.581 0.604 0.175 0.0429], ...
	'String','Valeur max', ...
	'Style','text') ;

% zone edit de la Valeur max
% --------------------------

h_VMAX = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',['global vmax;', ...
		    'VALMAX = str2num(get(gco,''String''));', ...
		    'if VALMAX > vmax,', ...
			'VALMAX = vmax;', ...
		    'end;'], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[369.6 186.4 58.4000 23.2], ...
	'String',vmax, ...
	'Style','edit') ;
	
% zone de texte "pas d'echantillonnage"
% -------------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.5456 0.4986 0.2857 0.05], ...
	'String','Pas d''echantillonnage', ...
	'Style','text') ;

% zone edit du pas d'echantillonnage
% -----------------------------------

h_ECHANT = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',('ECHANT_REF = str2num(get(gco,''String''));'), ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[369.6 152.8 58.4000 23.2], ...
	'String',echant, ...
	'Style','edit') ;

% bouton "Changer de parametre de reference"
% ------------------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7020 0.7020 0.7020], ...
	'Callback','param_ref_choisi', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.05 0.25 0.5071 0.1119], ...
	'String','Changer de parametre de reference') ;
	
% bouton "Ok"
% -----------

% modif C. Lagadec (mai 2000) pour le parametre zzz
% -------------------------------------------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7020 0.7020 0.7020], ...
	'Callback',['global vmin vmax code;', ...
		    'if isempty(VALMIN),VALMIN = vmin;end;', ...
		    'if isempty(VALMAX),VALMAX = vmax;end;', ...
		    'if isempty(ECHANT_REF),ECHANT_REF = ETIQ.interv;end;', ...
		    'if isempty(CODE_REF),CODE_REF = code;end;', ...
            'if  (CODE_REF == ''ZCOO'' & VALMAX < VALMIN),', ...
                    '  GRILLE = [VALMAX:-ECHANT_REF:VALMIN];', ...
                    '  VALMIN = GRILLE(1);', ...
                    'else,', ...
		        '  GRILLE = [VALMIN:ECHANT_REF:VALMAX];', ... 
                    'end;', ...
    	    'VALMAX = GRILLE(length(GRILLE));', ...
		    'NB_NIV = length(GRILLE);', ...
 		    'close'], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.05 0.069 0.2411 0.1048], ...
	'String','Ok') ;

% bouton "Annuler"
% ----------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7020 0.7020 0.7020], ...
	'Callback',['global pass;', ...
		    'pass_ref = [];', ...
		    'CODE_REF = ''PRES'';', ...
		    'VALMAX = PMAXTOT;', ...
		    'VALMIN = PMINTOT;', ...
		    'ECHANT_REF = ETIQ.interv;', ...
		    'close'], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.3696 0.069 0.2411 0.1048], ...
	'String','Annuler') ;

% bouton "Aide"
% -------------

h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7020 0.7020 0.7020], ...
	'Callback','aides(1)', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.6875 0.069 0.2411 0.1048], ...
	'String','Aide') ;

if nargout > 0, fig = h0; end
