function recap_phys_mlt()

%---------------------------------------------
%  recapitulatif de tous les choix que         
%  l'utilisateur a pu faire precedemment,      
%  pour la creation des fichiers multistation  
%----------------------------------------------
 

globalVarEtiquni ;
globalVarDef ;
globalVarASCI ;
globalVMLT ;


% test pour determiner si les fichiers concernent des donnees en 
% descente ou en montee
% ----------------------------------------------------------------

if strcmp(upper(DIRECTION),'D')
	descmont = 'Descente' ;
else,
	descmont = 'Montee' ;
end ;


h0 = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'Name','Recapitulatif', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[0.4766 0.0537 0.5039 0.7188]);

% ------------------------------
% zone de texte "Campagne(s)"
% ------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.3922 0.9552 0.2403 0.0285], ...
	'String','Campagne', ...
	'Style','text') ;

% zone de texte "Nom(s) de(s) campagne(s)
% ----------------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.0481 0.8899 0.22 0.0476], ...
	'String','Campagne(s)', ...
	'Style','text') ;

% listbox du (ou des) nom(s) de campagne(s)
% -----------------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'FontSize',12, ...
	'Position',[0.0543 0.7609 0.2140 0.1168], ...
	'String',camp, ...
	'Style','listbox', ...
	'Value',1);

% zone de texte "Nombre de stations"
% ---------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.3891 0.8886 0.22 0.0462], ...
	'String','Nb stations', ...
	'Style','text');

% zone edit du nombre de stations
% --------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Enable','inactive', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.4217 0.8356 0.1457 0.0394], ...
	'String',NBFILES, ...
	'Style','edit') ;

% zone de texte "profil"
% -----------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.7256 0.8791 0.1519 0.0530], ...
	'String','Profil', ...
	'Style','text') ;

% zone edit profil  
% -----------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Enable','inactive', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.7333 0.8370 0.1519 0.0408], ...
	'String',descmont, ...
	'Style','edit') ;

% -------------------------
% zone de texte Niveaux
% -------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.3938 0.7120 0.1891 0.0353], ...
	'String','Niveaux', ...
	'Style','text') ;

% zone de texte "Premier Niveau"
% -------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.0744 0.67 0.1736 0.0313], ...
	'String','Premier niveau', ...
	'Style','text') ;

% zone edit du premier niveau
% ----------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Enable','inactive', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.0853 0.6141 0.1473 0.0408], ...
	'String',VALMIN, ...
	'Style','edit') ;

% zone de texte "Dernier niveau"
% ------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.3209 0.67 0.1736 0.0313], ...
	'String','Dernier niveau', ...
	'Style','text') ;	

% zone edit du dernier niveau
% ----------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Enable','inactive', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.3302 0.6141 0.1473 0.0408], ...
	'String',VALMAX, ...
	'Style','edit') ;
	
% zone de texte "Nombre de niveaux"
% ----------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.5535 0.67 0.1736 0.0313], ...
	'String','Nb niveaux', ...
	'Style','text') ;

% zone edit du nombre de niveaux
% ------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Enable','inactive', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.5690 0.6141 0.1473 0.0408], ...
	'String',NB_NIV, ...
	'Style','edit') ;

% zone de texte "Pas d'echantillonnage"
% -------------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.7597 0.67 0.1736 0.0313], ...
	'String','Pas d''echantillonnage', ...
	'Style','text') ;

% zone edit du pas d'echantillonnage
% -----------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Enable','inactive', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.7984 0.6141 0.1473 0.0408], ...
	'String',ECHANT_REF, ...
	'Style','edit') ;
	
% -------------------------------
% zone de texte "Parametres"
% -------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'FontWeight','bold', ...
	'ListboxTop',0, ...
	'Position',[0.3767 0.5380 0.2465 0.0448], ...
	'String','Parametres', ...
	'Style','text') ;
	
% zone de texte "Code du parametre de reference"
% ----------------------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.0434 0.4891 0.4077 0.0394], ...
	'String','Code du parametre de reference ', ...
	'Style','text') ;
	

% zone edit du code du parametre de reference
% --------------------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Enable','inactive', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.4899 0.4986 0.1349 0.0394], ...
	'String',CODE_REF, ...
	'Style','edit') ;

% zone de texte "Parametres physiques"
% -------------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.16 0.35 0.2946 0.0313], ...
	'String','Parametres physiques', ...
	'Style','text') ;

% listbox des codes des parametres physiques choisis prealablement 
% par l'utilisateur, et qui apparaîtront donc dans le fichier 
% multistation qui sera cree par la suite
% ------------------------------------------------------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'FontSize',12, ...
	'Position',[0.49 0.20 0.1395 0.2514], ...
	'String',CODES_PARAMP_CHOISI, ...
	'Style','listbox', ...
	'Value',1);

% bouton "Modifier"
% ------------------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.7020 0.7020 0.7020], ...
	'Callback','close', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.168 0.06 0.2279 0.0598], ...
	'String','Modifier') ;

% bouton "Ok"
% -----------

uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0.702 0.702 0.702], ...
	'Callback',('creat_phys_mlt;close,'), ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.578 0.06 0.2279 0.0598], ...
	'String','Ok');



if nargout > 0, fig = h0; end
