function charg_sav ()
 
%-------------------------------------------
%
% Saisie du nom et lecture d'un fichier .sav 
%
% C.Lagadec - Nov 98
%
%-------------------------------------------
                    
globalVarEtiquni

globalRepDef;
global  nom_sav;

a = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Name','Choix d''un fichier .sav', ...   
        'NumberTitle','off',...
        'MenuBar','none',...
	'Position',[0.448785 0.502222 0.5 0.2]);


uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'HorizontalAlignment','left', ...
	'Position',[0.03 0.44 0.3 0.15], ...
	'String','Fichier Options', ...
	'Style','text');

nom_sav = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
        'Callback',['NOMFIC_SAV=get(gco,''String'');', ...
                    'n=length(NOMFIC_SAV);', ...
                    'if NOMFIC_SAV(n-2:n) == ''sav'',', ...
                    'n = n-4;', ...
                    'end;', ...
                    'sufsav = ''.sav'';', ...
                    'NOMFIC_SAV=[NOMFIC_SAV(1:n) sufsav];'], ...
	'Position',[0.3 0.47 0.2 0.13], ...
	'Style','edit');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'Position',[0.5 0.44 0.1 0.15], ...
	'String','.sav', ...
	'Style','text');

hchoixcat = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'FontSize',15, ...
	'Position',[0.600694 0.483333 0.0885417 0.105556], ...
	'String','...', ...
	'Style','Pushbutton');

% initialisation du Callback du choix du fichier Options

Callchoix = ['global nom_sav NOMFIC_SAV,',...
             '[NOMFIC_SAV,DIRSERV] = sel_fic(''Choisir un fichier .sav'',''*.sav'',DIRSERV);', ... 
             'set(nom_sav,''String'',NOMFIC_SAV(1:length(NOMFIC_SAV)-4));'];

set(hchoixcat,'CallBack',Callchoix);

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback',['global NOMFIC_SAV DIRSERV ,', ...
                    'NOMFIC_SAV=[DIRSERV  NOMFIC_SAV];', ...
                    'iretour = lect_sav(NOMFIC_SAV);close;'], ...
	'FontSize',12, ...
	'Position',[0.03 0.1 0.2 0.15], ...
	'String','OK', ...
	'Style','Pushbutton');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback',['global NOMSAV_DEF ,', ...
                    'NOMSAV_DEF = ''creclc_def.sav'';', ...
                    'iretour = lect_sav(NOMSAV_DEF);close;'], ...
	'FontSize',12, ...
	'Position',[0.7 0.1 0.2 0.15], ...
	'String','Annuler', ...
	'Style','Pushbutton');
