function choix_repserv ()

% ------------------------------------------------
%
%  fonction choix_repserv   -  C.Lagadec - fev.99
%
%   choix du repertoire 'service' 
%   par defaut sous le repertoire de lecture
% 
% ------------------------------------------------



globalRepDef;
global serv;

serv = DIRSERV;

DIRSERV = '';

a = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'Name','Choix du repertoire service', ...
	'NumberTitle','off', ...
	'Position',[0.50 0.52 0.45 0.15]);

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback',['global serv, if  isempty(DIRSERV),', ...
                            'DIRSERV = serv;', ...
                            'if ~exist(DIRSERV,''dir''),', ...
                            'mkdir(REPLECT,''service/''),', ...
                    'end,end,', ...
                    'close,'], ...
	'FontSize',13, ...
	'ListboxTop',0, ...
	'Position',[0.13 0.1 0.22 0.21], ...
	'String','Ok');

% repertoire de service
% ---------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',['DIRSERV=get(gco,''String'');', ...
                       'ir = length(DIRSERV);', ...
                       'if  DIRSERV(ir) ~= ''/'',', ...
                              'DIRSERV = [DIRSERV ''/''];', ...
                       'end;', ...
                    'if ~exist(DIRSERV,''dir''),', ...
                       'parentdir = DIRSERV(1:ir-8),', ...
                       'mkdir(parentdir,''service/''),', ...
                    'end'], ...
	'FontSize',10, ...
	'Position',[0.11 0.48 0.78 0.20], ...
	'String',serv,...
        'HorizontalAlignment','left', ...
	'Style','edit');


% Pushbutton de sortie d'ecran
% ----------------------------

% -> Annuler

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','close', ...
	'FontSize',13, ...
	'Position',[0.73 0.1 0.22 0.21], ...
	'String','Annuler');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.2 0.74 0.37 0.11], ...
	'String','Repertoire service', ...
	'Style','text');
