function choix_envir_cli ()

% ----------------------------------------------------------
%
%  choix_envir_cli : C.Lagadec   - Dec.98
%
% choix des repertoires de lecture et d'ecriture
% le repertoire 'resu' se situe sous le repertoire d'ecriture
% s'il n'existe pas, on le cree
%
% fonction utilisee par creclc, cremlt_phys et creasc
%
% ----------------------------------------------------------


globalRepDef;

a = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'Name','Environnement de travail', ...
	'NumberTitle','off', ...
	'Position',[0.44 0.5 0.45 0.22]);

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback',['DIRRESU = [REPECR ''resu/''];', ...
                    'if ~exist(DIRRESU,''dir''),', ...
                            'mkdir(REPECR,''resu''),', ...
                    'end,', ...
                    'close,', ...
                    'choix_repserv,'], ...
	'FontSize',13, ...
	'ListboxTop',0, ...
	'Position',[0.13 0.1 0.22 0.16], ...
	'String','Ok');

% repertoire de lecture
% ---------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'Callback',['REPLECT=get(gco,''String'');', ...
                     'if ~exist(REPLECT,''dir''),', ...
                           'h = warndlg(''Le repertoire de lecture n''''existe pas  !'',''Erreur'');', ...
                           'waitfor(h);', ...
                      'else,', ...
                          'ir = length(REPLECT);', ...
                          'if  REPLECT(ir) ~= ''/'',', ...
                              'REPLECT = [REPLECT ''/''];', ...
                          'end;', ...
                          'DIRSERV = [REPLECT ''service/''];', ...
                          'end'], ...
	'FontSize',10, ...
	'Position',[0.40 0.75 0.60 0.14], ...
	'String',REPLECT,...
        'HorizontalAlignment','left', ...
	'Style','edit');


% repertoire d'ecriture
% ---------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Callback',['REPECR=get(gco,''String'');', ...
                    'if ~exist(REPECR,''dir''),', ...
                           'h = warndlg(''Le repertoire d''''ecriture n''''existe pas  !'',''Erreur'');', ...
                           'waitfor(h);', ...
                      'else,', ...
                          'ir = length(REPECR);', ...
                          'if  REPECR(ir) ~= ''/'',', ...
                              'REPECR = [REPECR ''/''];', ...
                          'end;', ...
                     'end'], ...
	'FontSize',10, ...
	'Position',[0.40 0.58 0.60 0.14], ...
	'String',REPECR,...
        'HorizontalAlignment','left', ...
	'Style','edit');


% Pushbutton de sortie d'ecran
% ----------------------------

% -> Annuler

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','close', ...
	'FontSize',13, ...
	'Position',[0.73 0.1 0.22 0.16], ...
	'String','Annuler');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...	
        'Position',[0.03 0.78 0.37 0.11], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'String','Repertoire de lecture', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...	
	'Position',[0.03 0.58 0.37 0.11], ...
	'String','Repertoire d''ecriture', ...
	'Style','text');
