function complementation()


globalVarEtiquni; 

globalVarDef;

global ppmin ppmax; 

if  isempty(PMININT_DEF)
        ppmin = 0;
     else
        ppmin = PMININT_DEF;
end;

if  isempty(PMAXINT_DEF)
        ppmax = PMAXTOT;
     else
        ppmax = PMAXINT_DEF;
end;

a = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Name','Complementation', ...
        'NumberTitle','off',...
        'MenuBar','none',...
	'Position',[0.26 0.36 0.6 0.45]);
 
uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',15, ...
	'Position',[0.0492041 0.9 0.924747 0.0733333], ...
	'String','La complementation (surface et milieu) est faite systematiquement.', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontSize',15, ...
	'Position',[0.13 0.81 0.47 0.08], ...
	'String','Definition de la grille intermediaire', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'Position',[0.02 0.69 0.20 0.049], ...
	'String','Pression mini fichiers', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'Position',[0.02 0.63 0.20 0.049], ...
	'String','Pression maxi fichiers', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontSize',15, ...
	'Position',[0.15 0.49 0.33 0.051], ...
	'String','Complement de surface', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'Position',[0.08 0.41 0.26 0.054], ...
	'String','Taille maxi du trou complete', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontSize',15, ...
	'Position',[0.11 0.27 0.44 0.071], ...
	'String','Complement milieu de profil', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'Position',[0.05 0.19 0.30 0.05], ...
	'String','Taille maxi du trou complete', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'Position',[0.04 0.09 0.29 0.05], ...
	'String','Mode d''interpolation', ...
	'Style','text');


% mode interpolation (lineaire ou  spline)
% -------------------------------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'FontSize',11, ...
        'Callback',['MODINT_DEF = get(gco,''Value'');', ...
                    'if MODINT_DEF == 1;', ...
                        'MODINT_DEF = ''Spline''; ', ...
                           'else;', ...
                        'MODINT_DEF = ''Lineaire''; ', ...
                    'end;'], ...
	'Position',[0.37 0.08 0.12 0.066], ...
	'String',['Spline  ';'Lineaire'], ...
	'Style','popupmenu', ...
	'Value',2);

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'CallBack', 'TROUSURF_DEF = str2num(get(gco,''String''));', ...
	'FontSize',11, ...
        'String',TROUSURF_DEF, ...
	'Position',[0.37 0.42 0.09 0.05], ...
	'Style','edit');

% PMINTOT : pression mini de tous les fichiers
% --------------------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
        'Enable','inactive', ...
	'FontSize',11, ...
        'String', PMINTOT, ...
	'Position',[0.25 0.70 0.11 0.06], ...
	'Style','edit');

% PMAXTOT : pression maxi de tous les fichiers
% --------------------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ... 
        'Enable','inactive', ...
	'FontSize',11, ...
	'Position',[0.25 0.63 0.11 0.06], ... 
        'String', PMAXTOT, ...
	'Style','edit');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'CallBack', 'TROUMIL_DEF = str2num(get(gco,''String''));', ...
	'FontSize',11, ...
        'String', TROUMIL_DEF, ...
	'Position',[0.37 0.19 0.1 0.05], ...
	'Style','edit');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'Position',[0.55 0.42 0.14 0.04], ...
	'String','Hauteur', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ... 
        'CallBack', 'HAUTSURF_DEF = str2num(get(gco,''String''));', ...
        'FontSize',11, ...
        'String',HAUTSURF_DEF, ...
	'Position',[0.68 0.42 0.1 0.056], ...
	'Style','edit');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'Position',[0.42 0.78 0.11 0.04], ...
	'String','Pas', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'Position',[0.38 0.69 0.16 0.05], ...
	'String','Pression mini', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',11, ...
	'Position',[0.38 0.63 0.16 0.05], ...
	'String','Pression maxi', ...
	'Style','text');

% Pas de la grille intermediaire
% ------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'CallBack','PASINT_DEF = str2num(get(gco,''String''));', ...
	'FontSize',11, ...
        'String', PASINT_DEF, ...
	'Position',[0.57 0.77 0.06 0.056], ...
	'Style','edit');

% Pression mini de la grille intermediaire
% ----------------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'CallBack','PMININT_DEF = str2num(get(gco,''String''));', ...
	'FontSize',11, ...
	'Position',[0.57 0.70 0.11 0.06], ...
        'String', ppmin, ...
	'Style','edit');

% Pression maxi de la grille intermediaire
% ----------------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'CallBack','PMAXINT_DEF = str2num(get(gco,''String''));', ...
	'FontSize',11, ...
	'Position',[0.57 0.63 0.11 0.06], ... 
        'String', ppmax, ...
	'Style','edit');

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontSize',15, ...
	'Position',[0.79 0.83 0.15 0.05], ...
	'String','Decimation', ...
	'Style','text');

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.73 0.74 0.089 0.059], ...
	'String','Pas', ...
	'Style','text');

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
        'CallBack','PASDECIM_DEF = str2num(get(gco,''String''));', ...
        'String', PASDECIM_DEF, ...
	'Position',[0.85 0.74 0.072 0.07], ...
	'Style','edit');



% bouton OK : appel de la fenetre pour la decimation
% --------------------------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'Callback',['global ppmin ppmax;', ...
                    'if isempty(PMININT_DEF),', ...
                       'PMININT_DEF = ppmin;end;', ...
                    'if isempty(PMAXINT_DEF),', ...
                       'PMAXINT_DEF = ppmax;end;', ...
                'if mod(PASDECIM_DEF,PASINT_DEF)>0,', ...
                    '   h = warndlg(''Le pas de la grille finale doit etre un multiple du pas de la grille intermediaire.'',''Erreur'');', ...
                    '   waitfor(h);', ...
                    ' else,', ...
                    '   close, gril_interm,end'], ...
	'FontSize',13, ...
	'Position',[0.8 0.16 0.12 0.07], ...
	'String','OK');
