globalVarEtiquni;

globalVarDef;

globalRepDef; 

global hsuivi;

messtat  = 'Vous devez d''abord choisir les fichiers a traiter.';
messcomp = 'Complementation obligatoire';


init_cre;


global isav;
isav = [];


f = figure('Units','normalized', ...
           'Color',[0.8 0.8 0.8], ...
           'Name','Creclc', ...
           'NumberTitle','off', ...
	       'Position',[0.45 0.81 0.54 0.12], ...
           'MenuBar','none');

% ----------------------------------------
% chargement du fichier Options par d�faut
% ----------------------------------------

NOMSAV_DEF = 'creclc_def.sav';
iretour = lect_sav(NOMSAV_DEF);
if iretour == 1 
    clear all
    close all
   return
end

% CONFIGURATION
% =============

h1=uimenu(f,'Label','Configuration');

uimenu(h1,'Label','Environnement de travail ...',...
                'Separator', 'off', ...
                'Callback','choix_envir_cli');

% ---------------------------------------------------------

% STATIONS
% --------

h3 = uimenu(f,'Label','Stations');

% sous menus du menu stations 
% ---------------------------

uimenu(h3,'Label','Suite continue ...', ...
                'Separator','off', ...
                'Callback','suf = ''_cli.nc''; stat_suit;');

uimenu(h3,'Label','Catalogue ...', ...
                'Separator','on', ...
                'Callback',['global masq_cat;', ...
                            'masq_cat = ''*cli.cat'';', ...
                            'stat_cat(masq_cat);']);

uimenu(h3,'Label','Repertoire ...', ...
                'Separator','on', ...
                'Callback',' suf=''cli.nc'';stat_rep');


% ---------------------------------------

h4 = uimenu(f,'Label','Parametrage ');


uimenu(h4,'Label','Complementation ...', ...
             'CallBack',['if (isempty(ETIQ.codes_paramp)),', ...
			     'h=warndlg(messtat,''Attention'');', ...
                             'waitfor(h),', ...
		           'else, complementation; end']);

uimenu(h4,'Label','Lissage ...', ...
                  'Separator','on', ...
	              'CallBack',['if (isempty(ETIQ.codes_paramp)),', ...
			                     'h=warndlg(messtat,''Attention'');', ...
                                 'waitfor(h),', ...
                            'elseif (isempty(P_INT)),', ...
                                 'h=warndlg(messcomp, ''Attention'');', ...
                                 'waitfor(h),', ...
                            'else, lissage; end']);


% ---------------------------------------

h5 = uimenu(f,'Label','Creation des Fichiers ');


uimenu(h5,'Label','Recapitulatif ...', ...
             'CallBack',['global icharg;', ...
                         'if (isempty(P_INT)),', ...
                         '    if icharg == 1,', ...
                         '        gril_interm;', ...
                         '     else,', ...
			 '        warndlg(messcomp,''Attention'');', ...
                         '    end;', ...
		         'else, voschoix_clc; end']);

uimenu(h5,'Label','Creation ...', ...
                'Separator','on', ...
	        'CallBack',['global icharg;', ...
                            'if (isempty(P_INT)),', ...
                            '    if icharg == 1,', ...
                            '        gril_interm;', ...
                            '     else,', ...
			    '        warndlg(messcomp,''Attention'');', ...
                            '    end;', ...
                            ' else, creat_clc ; end']);


% -----------------------------------------


% bouton Quitter application
% --------------------------

h6 = uimenu(f, 'Label', 'Quitter ');

uimenu(h6,'Label','Quitter l''application', ...
          'Callback','clear all,close all');


% -----------------------------------------------------------------


% Titre de l'interface
% ---------------------

uicontrol('Parent',f, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',16, ...
	'Position',[0.2 0.50 0.45 0.2], ...
	'String','CREATION DES FICHIERS', ...
	'Style','text');
uicontrol('Parent',f, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',16, ...
	'Position',[0.2 0.20 0.45 0.2], ...
	'String','CALCULES', ...
	'Style','text');


% Zone du logo
% ------------
	
axes('position',[0.75 0.1 0.2 0.8]);

% Logo
% ----

[x map]=imread('lpo.jpg');
image(x);
colormap(map);
axis off;




clear current;
