function   lisscren (j) 

% --------------------------------------------
%
% lisscren : Auteur C.Lagadec (dec 99)
%
% Determination du parametre 'largeur'
% dans le cas de lissage créneau
%
% --------------------------------------------

% j = numero d'ordre du param dans la liste des param. a lisser
% =============================================================

globalVarDef;

global h_P1 h_P2 h_TYPLISS_DEF;

larg_c = '';

a = figure('Units','normalized', ...
	   'Color',[0.8 0.8 0.8], ...
	   'Position',[0.64 0.4 0.31 0.15], ...
 	   'Name','Lissage Créneau', ...
           'NumberTitle','off',...
           'MenuBar','none');

uicontrol('Parent',a, ...
	   'Units','normalized', ...
	   'BackgroundColor',[1 1 1], ...
           'String',C_LARG_DEF, ...
           'Callback','global larg_c;larg_c  = str2num(get(gco,''String''));', ...
           'Fontsize',12, ...
	   'Position',[0.6 0.71 0.1 0.18], ...
	   'Style','edit');


uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Largeur', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'Fontsize', 12, ...
	'Position',[0.2 0.71 0.26 0.18], ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Ok', ...
        'Callback',['global h_P1 h_P2 h_TYPLISS_DEF;', ...
                    'global larg_c ;', ...
                    'if (isempty(larg_c)),', ... 
                    'P1_DEF(j) = C_LARG_DEF;', ...
                    'else,', ...
                    'P1_DEF(j) = larg_c; end,', ...
                    'larg_c = '''';', ...
                    'P2_DEF(j) = zeros;', ...
                    'TYPLISS_DEF(j,:) = ''Creneau    '';', ...
                    'set(h_P1,''String'',P1_DEF);', ...
                    'set(h_P2,''String'',P2_DEF);', ...
                    'set(h_TYPLISS_DEF ,''String'',TYPLISS_DEF);', ...
                    'close,'], ...
        'Fontsize', 12, ...
	'Position',[0.15 0.26 0.21 0.21], ...
	'Style','Pushbutton');


% bouton Annuler
% --------------
uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Annuler', ...
        'Callback',['global h_P1 h_P2 h_TYPLISS_DEF;', ...
                    'TYPLISS_DEF(j,1:11) = '' '';', ...
                    'set(h_TYPLISS_DEF,''String'',TYPLISS_DEF);', ...
                    'P1_DEF(j) = zeros;', ...
                    'set(h_P1,''String'',P1_DEF);', ...
                    'P2_DEF(j) = zeros;', ...
                    'set(h_P2,''String'',P2_DEF);', ...
                    'close,'] , ...
        'Fontsize', 12, ...
	'Position',[0.6 0.26 0.21 0.21], ...
        'Style','Pushbutton');


% bouton AIDE pour demi-largeur du filtre
% ---------------------------------------


uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String', 'Aide', ...
        'Callback', 'aide(2)', ...
        'Fontsize', 12, ...
	'Position',[0.8 0.71 0.1 0.18]);

