function   lisslanc (j)

% determination des parametres 'largeur et ecart-type'
% dans le cas de lissage de lanczos
% ----------------------------------------------------

globalVarDef;

larg_l = '';
freq_l = '';

a = figure('Units','normalized', ...
	   'Color',[0.8 0.8 0.8], ...
	   'Position',[0.64 0.4 0.31 0.15], ...
 	   'Name','Lissage de Lanczos', ...
           'NumberTitle','off',...
           'MenuBar','none');


uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'String',L_LARG_DEF , ...
        'Callback', 'global larg_l;larg_l = str2num(get(gco,''String''));', ...
        'Fontsize', 12, ...
	'Position',[0.6 0.71 0.1 0.18], ...
	'Style','edit');

uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Largeur', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
        'Fontsize', 12, ...
	'Position',[0.2 0.71 0.26 0.18], ...
	'Style','text');


% bouton AIDE pour demi-largeur du filtre
% ---------------------------------------


uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String', 'Aide', ...
        'Callback', 'aide(2)', ...
        'Fontsize', 12, ...
	'Position',[0.8 0.71 0.1 0.18]);


% frequence de coupure
% --------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Fréq. de coupure', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
        'Fontsize', 12 , ...
	'Position',[0.1 0.3 0.32 0.2], ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'String',L_FREQ_DEF , ...
        'Callback', 'global freq_l;freq_l = str2num(get(gco,''String''));', ...
        'Fontsize', 12, ...
	'Position',[0.6 0.35 0.1 0.18], ...
	'Style','edit');

% bouton AIDE pour frequence de coupure
% -------------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String', 'Aide', ...
        'Callback', 'aide(3)', ...
        'Fontsize', 12, ...
	'Position',[0.8 0.35 0.1 0.18]);


% bouton OK
% ---------
uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Ok', ...
        'Callback',['global h_P1 h_P2 h_TYPLISS_DEF;', ...
                    'global larg_l  freq_l;', ...
                    'if (isempty(larg_l)),', ...
                        'P1_DEF(j) = L_LARG_DEF;', ...
                      'else,', ...
                        'P1_DEF(j) = larg_l; end,', ...
                    'larg_l = '''';', ...
                    'if (isempty(freq_l)),', ...
                        'P2_DEF(j) = L_FREQ_DEF;', ...
                      'else,', ...
                        'P2_DEF(j) = freq_l; end,', ...
                    'freq_l = '''';', ...
                    'TYPLISS_DEF(j,1:11) = ''Lanczos    '';', ...
                    'set(h_P1,''String'',P1_DEF);', ...
                    'set(h_P2,''String'',P2_DEF);', ...
                    'set(h_TYPLISS_DEF ,''String'',TYPLISS_DEF);', ...
                    'close,'], ...
        'Fontsize', 12, ...
	'Position',[0.2 0.06 0.21 0.21], ...
        'Style','Pushbutton');


% bouton Annuler
% --------------
uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Annuler', ...
        'Callback',['global h_P1 h_P2 h_TYPLISS_DEF;', ...
                    'TYPLISS_DEF(j,1:11) = '' '';', ...
                    'set(h_TYPLISS_DEF,''String'',TYPLISS_DEF);', ...
                    'P1_DEF(j) = zeros;', ...
                    'P2_DEF(j) = zeros;', ...
                    'set(h_P1,''String'',P1_DEF);', ...
                    'set(h_P2,''String'',P2_DEF);', ...
                    'close,'] , ...
        'Fontsize', 12, ...
	'Position',[0.6 0.06 0.21 0.21], ...
        'Style','Pushbutton');
