function lissage()

globalVarEtiquni;

global PARLISS NOMLISS param;

globalVarDef;
NOMLISS =['Creneau    ';'Lanczos    ';'Butterworth';'Aucun      '];

global h_P1 h_P2 h_TYPLISS_DEF;

% Fenetre de saisie des parametres a lisser 

figliss = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Name','Parametres a lisser', ...
        'NumberTitle','off',...
        'MenuBar','none',...
	'Position',[0.43 0.42 0.4 0.31 ]);

% Parametres  (txt)
uicontrol('Parent',figliss, ...
	'Units','normalized', ...
	'FontSize',12, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[0.010 0.88 0.28 0.06], ...
	'String','Param. a lisser', ...
	'Style','text');

%Codes des parametres  (listbox)
%-------------------------------

h_codesL=uicontrol('Parent',figliss, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[0.06 0.44 0.15 0.36], ...
	'FontSize',11, ...
	'Style','listbox', ...
        'String',ETIQ.codes_paramp(2:ETIQ.nparp,:), ...
	'Value',1);

% Paramètre choisi
% ----------------

uicontrol('Parent',figliss, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.04 0.25 0.19 0.062], ...
	'String','Selection', ...
	'Style','text');

PARLISS = uicontrol('Parent',figliss, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
	'Position',[0.08 0.13 0.10 0.1], ...
	'Style','edit');

% affichage du lissage
% --------------------

h_TYPLISS_DEF =  uicontrol('Parent',figliss, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Style','listbox', ...
	'Position',[0.26 0.44 0.2 0.36], ...
        'FontSize',11, ...
        'String',TYPLISS_DEF);

uicontrol('Parent',figliss, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.386 0.88 0.182 0.068], ...
	'String','Lissage', ...
	'Style','text');


% Initialisation du Callback du parametre a� lisser (PARLISS)
% ----------------------------------------------------------

lCodecall = ['global  PARLISS param;', ...
             'val=get(gco,''Value'');',...
             'param=ETIQ.codes_paramp(val+1,:);', ...
             'set(PARLISS,''String'',param);'];
 
set(h_codesL,'CallBack',lCodecall);


uicontrol('Parent',figliss, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'FontSize',12, ...
	'Position',[0.27 0.13 0.3 0.1], ...
	'String',NOMLISS, ...
	'Style','popupmenu', ...
        'Value',4, ...
        'CallBack',['global  NOMLISS param ;', ...
                    'globalVarEtiquni;', ...
                    'globalVarDef;', ...
                    'choixliss = get(gco,''value'');', ...
                    'for i = 1:ETIQ.nparp,', ...
                        'if ~isempty(strmatch(ETIQ.codes_paramp(i,:),param)),', ...
                           'j = i-1;', ...
                        'end;', ...
                    'end;', ...
                    'switch choixliss,', ...
                       'case 1,j,lisscren(j);', ...
                       'case 2,j,lisslanc(j);',...
                       'case 3,j,lissstand(j);', ...
                       'case 4,global h_P1 h_P2 h_TYPLISS_DEF;', ...
                             'TYPLISS_DEF(j,1:11) = '' '';', ...
                             'set(h_TYPLISS_DEF,''String'',TYPLISS_DEF);', ...
                             'P1_DEF(j) = zeros;', ...
                             'set(h_P1,''String'',P1_DEF);', ...
                             'P2_DEF(j) = zeros;', ...
                             'set(h_P2,''String'',P2_DEF);end']);

% affichage des parametres de lissage
% -----------------------------------


h_P1 = uicontrol('Parent',figliss, ...
        'Units','normalized', ...
        'BackgroundColor',[1 1 1], ...
        'FontSize',12, ...
        'Position',[0.5 0.44 0.08 0.36], ...
        'String',P1_DEF, ...
        'Style','listbox');


h_P2 = uicontrol('Parent',figliss, ...
        'Units','normalized', ...
        'BackgroundColor',[1 1 1], ...
        'FontSize',12, ...
        'Position',[0.6 0.44 0.08 0.36], ...
        'String',P2_DEF, ...
        'Style','listbox');

% Quitter (push)
% --------------

uicontrol('Parent',figliss, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'FontSize',12, ...
        'Style','PushButton', ...
        'Callback','close', ...
	'Position',[0.75 0.28 0.21 0.12], ...
	'String','Ok');

uicontrol('Parent',figliss, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'FontSize',12, ... 
        'Callback','close', ...
	'Position',[0.75 0.1 0.21 0.12], ...
	'String','Annuler');


clear current;
