function lissparam(param)

a = figure('Color',[0.8 0.8 0.8], ...
        'NumberTitle','off',...
        'MenuBar','none',...
	'Name','Lissage', ...
	'Position',[517 331 560 420]);

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.02 0.84 0.205357 0.0595238], ...
	'String','Paramètre', ...
	'Style','text');

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'String',param,...
	'FontSize',12, ...
	'Position',[0.3 0.76 0.08 0.15], ...
	'Style','edit');

% Choix du type de lissage
% ------------------------

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontSize',12, ... 
        'CallBack',['h=get(gco,''UserData'');',...
                    'CHOIXLISS = get(gco,''value'');',...
                    'hui=gco;',...
                    'if CHOIXLISS == 1,' ,...
                    'set(hui,''UserData'',[]);',...
                    'h=lisscren(gcf);',...
                    'set(hui,''UserData'',h);',...
                    'elseif CHOIXLISS == 2,',...
                    'set(hui,''UserData'',[]);',...
                    'h=lisslanc(gcf);',...
                    'set(hui,''UserData'',h);',...
                    'elseif CHOIXLISS == 3,',...
                    'set(hui,''UserData'',[]);',...
                    'h=lissstand(gcf);',...
                    'set(hui,''UserData'',h);',...
                    'end;'],...
	'Position',[0.42 0.84 0.208929 0.0547619], ...
	'String',['Créneau ';'Lanczos ';'Standard';'Aucun   '], ...
	'Style','popupmenu', ...
	'Value',1);

% boutons de sortie
% -----------------

b = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','close', ...
	'FontSize',13, ...
	'Position',[0.8 0.29 0.17 0.086], ...
	'String','Ok');

