function   lissstand (j)

% determination du parametre Periode de coupure
% dans le cas de lissage Butterworth
% -----------------------------------------------

globalVarDef;

period_b = '';
ordr_b   = '';

a = figure('Units','normalized', ...
	   'Color',[0.8 0.8 0.8], ...
	   'Position',[0.64 0.4 0.31 0.15], ...
 	   'Name','Lissage Butterworth', ...
           'NumberTitle','off',...
           'MenuBar','none');


uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'String', B_PERIOD_DEF, ...
        'Callback', 'global period_b;period_b = str2num(get(gco,''String''));', ...
        'Fontsize', 12, ...
	'Position',[0.6 0.71 0.1 0.18], ...
	'Style','edit');

uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Période de coupure', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
        'Fontsize', 12, ...
	'Position',[0.08 0.71 0.4 0.18], ...
	'Style','text');

% bouton AIDE pour période de coupure
% -------------------------------------


uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String', 'Aide', ...
        'Callback', 'aide(7)', ...
        'Fontsize', 12, ...
	'Position',[0.8 0.71 0.1 0.18]);



% ordre du filtre
% ---------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Ordre du filtre', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
        'Fontsize', 12 , ...
	'Position',[0.20 0.29 0.28 0.2], ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'String',B_ORDR_DEF , ...
        'Callback', 'global ordr_b;ordr_b = str2num(get(gco,''String''));', ...
        'Fontsize', 12, ...
	'Position',[0.6 0.35 0.1 0.18], ...
	'Style','edit');

% bouton AIDE pour ordre
% ------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String', 'Aide', ...
        'Callback', 'aide(13)', ...
        'Fontsize', 12, ...
	'Position',[0.8 0.35 0.1 0.18]);


% bouton Annuler
% --------------
uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Annuler', ...
        'Callback',['global h_P1 h_P2 h_TYPLISS_DEF;', ...
                    'P1_DEF(j) = zeros;', ...
                    'P2_DEF(j) = zeros;', ...
                    'TYPLISS_DEF(j,1:11) = '' '';', ...
                    'set(h_P1,''String'',P1_DEF);', ...
                    'set(h_P2,''String'',P2_DEF);', ...
                    'set(h_TYPLISS_DEF ,''String'',TYPLISS_DEF);', ...
                    'close,'], ...
        'Fontsize', 12, ...
	'Position',[0.6 0.06 0.21 0.21], ...
        'Style','Pushbutton');



% bouton OK
% ---------

uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Ok', ...
        'Callback',['global h_P1 h_P2 h_TYPLISS_DEF;', ...
                    'global period_b ordr_b;', ...
                    'if (isempty(period_b)),', ...
                       'P1_DEF(j) = B_PERIOD_DEF;', ...
                         'else,', ...
                       'P1_DEF(j) = period_b; end,', ...
                    'if (isempty(ordr_b)),', ...
                       'P2_DEF(j) = B_ORDR_DEF;', ...
                         'else,', ...
                       'P2_DEF(j) = ordr_b; end,', ...
                    'TYPLISS_DEF(j,:) = ''Butterworth'';', ...
                    'set(h_P1,''String'',P1_DEF);', ...
                    'set(h_P2,''String'',P2_DEF);', ...
                    'set(h_TYPLISS_DEF ,''String'',TYPLISS_DEF);', ...
                    'close,'], ...
        'Fontsize', 12, ...
	'Position',[0.2 0.06 0.21 0.21], ...
        'Style','Pushbutton');
