function modif_ident();

% ---------------------------------------------
% modif_ident : C.Lagadec - nov.98
                           
% fonction appellee par creat_clc
% possibilite de modifier l'identificateur 
% campagne lors de la creation des fichiers clc
% ---------------------------------------------

globalVarEtiquni;

fig_ident = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Name','Modification de l''identificateur Campagne ', ...
        'NumberTitle','off', ...
        'MenuBar','none',...
	'Position',[0.473958 0.531111 0.384549 0.156667]);


b = uicontrol('Parent',fig_ident, ...
	'Units','normalized', ...
	'FontSize',12, ...
        'Callback',['if length(IDENTCAMP)>8,', ...
                      'h=warndlg (''La longueur de l''''identificateur campagne doit etre inférieure a 8 !'',''Erreur'');', ...
                   'waitfor(h),', ...
                        'else,', ...
                      'close,', ...
                    'end;'], ...
	'Position',[0.77 0.18 0.15 0.25], ...
	'String','OK');

b = uicontrol('Parent',fig_ident, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.025 0.57 0.39 0.22], ...
	'String','Identificateur Campagne', ...
	'Style','text');

b = uicontrol('Parent',fig_ident, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
        'HorizontalAlignment','left', ...
        'String', IDENTCAMP , ...
        'CallBack','IDENTCAMP=get(gco,''String'');', ...
	'Position',[0.50 0.57 0.20 0.21], ...
	'Style','edit');

uiwait(fig_ident);

