function [imin,imax] = niv_visu_liss();

% ---------------------------------------------
% niv_visu_liss : C.Lagadec - mars 2000
%                          
% fonction appelee par creat_clc
%
% demande des niveaux mini et maxi a visualiser
% pour la vérification des paramètres de lissage
% ---------------------------------------------

globalVarEtiquni;

global pmindef pmaxdef P_INT pminvisu pmaxvisu;
global imin imax;

pmindef = P_INT(1);
pmaxdef = 100;


fig_niv = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Name','Verification du lissage (Niveaux de visualisation)', ...
        'NumberTitle','off', ...
        'MenuBar','none',...
	'Position',[0.473958 0.531111 0.384549 0.156667]);


b = uicontrol('Parent',fig_niv, ...
	'Units','normalized', ...
	'FontSize',12, ...
        'Callback',['global pmindef pmaxdef pminvisu pmaxvisu P_INT,', ...
                    'global imin imax;', ...
                    'if isempty(pminvisu),' ...
                       'pminvisu = pmindef;end;', ...
                    'if isempty(pmaxvisu),' ...
                       'pmaxvisu = pmaxdef;end;', ...
                    'if  pminvisu < P_INT(1),', ...   
                       'pminvisu = P_INT(1);end;', ...
                    'imin=find(P_INT==pminvisu);', ...
                    'if  pmaxvisu > P_INT(end),', ...   
                        'pmaxvisu = P_INT(end);end;', ...
                    'imax=find(P_INT==pmaxvisu);', ...
                    'if  isempty(imin) | isempty(imax),', ...
                              'h=warndlg(''Valeurs hors limites'');', ...
                              'waitfor(h);', ...
                        'else,', ...
                              'close,end'], ...
	'Position',[0.80 0.18 0.14 0.25], ...
	'String','OK');

% texte pression mini
% -------------------
uicontrol('Parent',fig_niv, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.025 0.57 0.60 0.22], ...
	'String','Pression mini (en decibars)', ...
	'Style','text');

% edit pression mini
% -------------------
uicontrol('Parent',fig_niv, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
        'String', pmindef, ...
        'HorizontalAlignment','center', ...
        'CallBack','global pminvisu,pminvisu=str2num(get(gco,''String''));', ...
	'Position',[0.65 0.59 0.14 0.21], ...
	'Style','edit');

% texte pression maxi
% -------------------
uicontrol('Parent',fig_niv, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.025 0.30 0.60 0.22], ...
	'String','Pression maxi (en decibars)', ...
	'Style','text');

% edit pression maxi
% -------------------
uicontrol('Parent',fig_niv, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
        'String', pmaxdef, ...
        'HorizontalAlignment','center', ...
        'CallBack','global pmaxvisu,pmaxvisu=str2num(get(gco,''String''));', ...
	'Position',[0.65 0.30 0.14 0.21], ...
	'Style','edit');

uiwait(fig_niv);
