function sauv_sav ()
%
%--------------------------------------------------------------
%
% Sauvegarde d'un fichier Options pour CRECLC 
%
% Création C.Lagadec - Nov 98
% Modification C.Lagadec _ Janvier 2012 pour adaptation HYDROCAL
%
%---------------------------------------------------------------

                   

globalRepDef;

global  nom_sav;

hsav = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Name','Sauvegarde du fichier des options', ...   
        'NumberTitle','off',...
        'MenuBar','none',...
	'Position',[0.5 0.55 0.5 0.2]);


uicontrol('Parent',hsav, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'HorizontalAlignment','left', ...
	'Position',[0.03 0.44 0.3 0.15], ...
	'String','Fichier Options', ...
	'Style','text');

nom_sav = uicontrol('Parent',hsav, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
        'Callback',['global ficsav,', ...
                    'ficsav=get(gco,''String'');', ...
                    'n=length(ficsav);', ...
                    'if ficsav(n-2:n) == ''sav'',', ...
                    'n = n-4;', ...
                    'end;', ...
                    'sufsav = ''.sav'';', ...
                    'ficsav=[ficsav(1:n) sufsav];'], ...
	'Position',[0.3 0.47 0.2 0.13], ...
	'Style','edit');

uicontrol('Parent',hsav, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'Position',[0.5 0.44 0.1 0.15], ...
	'String','.sav', ...
	'Style','text');

hchoixcat = uicontrol('Parent',hsav, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'FontSize',15, ...
	'Position',[0.600694 0.483333 0.0885417 0.105556], ...
	'String','...', ...
	'Style','Pushbutton');

% initialisation du Callback du choix du fichier Options

Callchoix = ['global nom_sav ficsav,',...
             '[ficsav,DIRSERV] = sel_fic(''Choisir un fichier .sav'',''*.sav'',DIRSERV);', ... 
             'set(nom_sav,''String'',ficsav);'];

set(hchoixcat,'CallBack',Callchoix);



uicontrol('Parent',hsav, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback',['global ficsav DIRSERV ,', ...
                    'ficsav  = [DIRSERV  ficsav],', ...
                    'iretour = ecr_sav(ficsav);', ...
                    'if iretour ~= 1,close,end;'], ...
	'FontSize',12, ...
	'Position',[0.03 0.1 0.2 0.15], ...
	'String','Ok', ...
	'Style','Pushbutton');

uicontrol('Parent',hsav, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','close', ...
	'FontSize',12, ...
	'Position',[0.7 0.1 0.2 0.15], ...
	'String','Annuler', ...
	'Style','Pushbutton');
uiwait(hsav);
