function suivi_creclc();

% variables pour la fenetre de suivi du traitement
global hsuivi hsuivi_cli hsuivi_clc hsuivi_err;
global ficuni_petit ficclc_petit messerr_suivi;

hsuivi = figure('Color',[0.8 0.8 0.8], ...
	'Name','Suivi du traitement', ...   
        'NumberTitle','off',...
        'MenuBar','none',...
	'Position',[414 41 564 247]);

uicontrol('Parent',hsuivi, ...
	'Units','normalized', ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[0.5621    0.7449    0.3156    0.1296], ...
	'String','Creation du fichier', ...
	'Style','text');

hsuivi_cli = uicontrol('Parent',hsuivi, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'String',ficuni_petit, ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'Position',[0.053 0.54 0.33 0.14], ...
	'Style','edit');

uicontrol('Parent',hsuivi, ...
	'Units','normalized', ...
	'FontSize',12, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'ListboxTop',0, ...
	'Position',[0.055 0.7368 0.3156 0.1296], ...
	'String','Traitement du fichier', ...
	'Style','text');

hsuivi_clc = uicontrol('Parent',hsuivi, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
        'String',ficclc_petit, ...
	'ListboxTop',0, ...
	'Position',[0.55 0.54 0.33 0.14], ...
	'Style','edit');

hsuivi_err = uicontrol('Parent',hsuivi, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',10, ...
        'String',messerr_suivi, ...
	'HorizontalAlignment','left', ...
	'Style','listbox', ...
	'Position',[0.11 0.09 0.75 0.39]);
if nargout > 0, fig = hsuivi; end
