function voschoix_clc()

% -------------------------------------------
% 
%  Fenetre recapitulative des choix pour la creation
%  des fichiers .clc
%
% -------------------------------------------

globalVarEtiquni;

globalVarDef;

descmont = 'Descente';
if strcmp(upper(DIRECTION),'A')
    descmont = 'Montee'; 
end;

% transformation de P1_DEF et P2_DEF en chaines de caracteres
% -----------------------------------------------------------
C1_DEF = sprintf('%4d',P1_DEF');
C1_DEF = strrep(C1_DEF,' 0','  ');
C1_DEF = reshape(C1_DEF, 5, 4);

C2_DEF = sprintf('%4.2f',P2_DEF');
C2_DEF = strrep(C2_DEF,'0.00','    ');
C2_DEF = reshape(C2_DEF, 5, 4);



figchoix = figure('Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'Name','Recapitulatif', ...
	'NumberTitle','off', ...
	'Position',[447 149 685 628], ...
	'Tag','Fig1');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
        'Enable','inactive', ...
        'String', IDENTCAMP, ...
	'FontSize',12, ...
	'Position',[0.079 0.846 0.128 0.057], ...
	'Style','edit');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
        'String', STAT1, ...
        'Enable','inactive', ...
	'FontSize',12, ...
	'Position',[0.292 0.846 0.128 0.057], ...
	'Style','edit');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
        'String', STATN, ...
        'Enable','inactive', ...
	'FontSize',12, ...
	'Position',[0.496 0.846 0.128 0.057], ...
	'Style','edit');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'FontSize',12, ...
        'Enable','inactive', ...
        'String', descmont, ...
	'Position',[0.689 0.846 0.128 0.057], ...
	'Style','edit');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.0803 0.9256 0.1227 0.0473], ...
	'String','Campagne', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.2924 0.9256 0.1227 0.0473], ...
	'String','1ere station', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.489 0.925 0.162 0.0472], ...
	'String','Derniere station', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.6879 0.9256 0.1758 0.0473], ...
	'String','Prelevements en', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontSize',15, ...
	'HorizontalAlignment','left', ...
	'Position',[0.02 0.77 0.24 0.052], ...
	'String','Echantillonnage', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
        'Enable','inactive', ...
        'String', PMININT_DEF, ...
	'FontSize',12, ...
	'Position',[0.086 0.6409 0.1095 0.057], ...
	'Style','edit');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
        'Enable','inactive', ...
        'String', P_FINAL(length(P_FINAL)), ...
	'FontSize',12, ...
	'Position',[0.297 0.6409 0.1095 0.057], ...
	'Style','edit');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
        'Enable','inactive', ...
	'ListboxTop',0, ...
        'String', PASDECIM_DEF, ...
	'FontSize',12, ...
	'Position',[0.506 0.6409 0.1095 0.057], ...
	'Style','edit');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontSize',16, ...
	'HorizontalAlignment','left', ...
	'Position',[0.02 0.516 0.2438 0.0526], ...
	'String','Extrapolation', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontSize',16, ...
	'HorizontalAlignment','left', ...
	'Position',[0.49 0.51 0.24 0.052], ...
	'String','Interpolation', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontAngle','italic', ...
	'FontSize',16, ...
	'HorizontalAlignment','left', ...
	'Position',[0.02 0.309 0.244 0.052], ...
	'String','Lissage', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.0803 0.7166 0.1212 0.0462], ...
	'String','Press min', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.2964 0.7166 0.1212 0.0462], ...
	'String','Press max', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.5051 0.7166 0.1212 0.0462], ...
	'String','Pas', ...
	'Style','text');


% Trou (texte et edit)
% -----------------------

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.0482 0.4347 0.1212 0.0478], ...
	'String','Trou', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
        'Enable','inactive', ...
        'String', TROUSURF_DEF, ...
	'Position',[0.1985 0.4411 0.1095 0.0573], ...
	'FontSize',12, ...
	'Style','edit');


% Hauteur (texte et edit)
% -----------------------

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.0584 0.3678 0.1226 0.0462], ...
	'String','Hauteur', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
        'Enable','inactive', ...
	'Position',[0.2015 0.3631 0.1095 0.0573], ...
	'FontSize',12, ...
        'String', HAUTSURF_DEF, ...
	'Style','edit');

% Trou milieu (texte et edit)
% ---------------------------

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.5270 0.4467 0.1212 0.0462], ...
	'String','Trou', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'FontSize',12, ...
        'Enable','inactive', ...
        'String', TROUMIL_DEF, ...
	'Position',[0.695 0.4415 0.1095 0.0575], ...
	'Style','edit');

% Mode interpolation (texte et edit)
% ---------------------------------

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.5270    0.3822    0.1212    0.0446], ...
	'String','Mode', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'HorizontalAlignment','left', ...
	'FontSize',12, ...
        'Enable','inactive', ...
        'String', MODINT_DEF, ...
	'Position',[0.695 0.379 0.1859 0.0469], ...
	'Style','edit');

%  Listbox des codes des parametres
% ---------------------------------
uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[0.05 0.03 0.128 0.2], ...
	'Style','listbox', ...
        'Enable', 'inactive', ...
	'FontSize',12, ...
        'String', ETIQ.codes_paramp(2:ETIQ.nparp,:), ...
	'Value',1);

%  Listbox des types de lissage 
% ------------------------------

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Position',[0.2058 0.03 0.1766 0.2054], ...
	'Style','listbox', ...
        'Enable', 'inactive', ...
	'FontSize',12, ...
        'String', TYPLISS_DEF, ...
	'Value',1);

%  Listbox des parametres de lissage (C1 et C2)
% --------------------------------------------


uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Position',[0.454 0.0255 0.0613 0.2054], ...
	'Style','listbox', ...
        'String', C1_DEF', ...
	'FontSize',12, ...
        'Enable', 'inactive', ...
	'Value',1);

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.9 0.9 0.9], ...
	'Position',[0.54 0.0255 0.0613 0.2054], ...
	'Style','listbox', ...
        'Enable', 'inactive', ...
	'FontSize',12, ...
        'String', C2_DEF', ...
	'Value',1);

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.02 0.2548 0.2117 0.05], ...
	'String','Parametres ', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.2102 0.2468 0.1504 0.059], ...
	'String','Type', ...
	'Style','text');

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.4584 0.258 0.1474 0.059], ...
	'String','Param. de lissage', ...
	'Style','text');


% Pushbutton : Modification
% -------------------------

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'FontSize',12, ...
        'Callback','close;', ...
	'Position',[0.7299 0.6513 0.2350 0.0780], ...
	'String','Modification des choix');

% Pushbutton : Creation
% -------------------------

uicontrol('Parent',figchoix, ...
	'Units','normalized', ...
	'BackgroundColor',[0.70196 0.70196 0.70196], ...
	'FontSize',12, ...
        'Callback','close;creat_clc;', ...
	'Position',[0.7343 0.5478 ,0.235 0.078], ...
	'String','Creation des fichiers');

if nargout > 0, fig = figchoix; end
