%------------------------------------------
%   stat_rep
%
%  fenetre de selection de stations dans le repertoire de donnees
%   utilise par creclc (uniquement pour fichiers cli)
%  => pas de bouton popup pour la selection du suffixe
%
%  C.Lagadec  (Nov. 98)
%
%
%------------------------------------------

function stat_rep()

globalVarEtiquni;

globalRepDef;

nomfsel = '';

REPLECT = deblank(REPLECT);
msgerr = '';

ista = 1;

if ~exist(REPLECT, 'dir') 
   msgerr = sprintf('%s %s %s', 'Le repertoire de donnees', REPLECT, 'n''existe pas');
end;

if (isempty(msgerr))

   mask = sprintf('%s%s', '*', suf);
   filtre = sprintf('%s%1c%s', REPLECT,  mask);

   files = '';
   ff    = dir(filtre);

   for ix=1:length(ff)
      if ((strcmp(ff(ix).name, '.') == 0) & (strcmp(ff(ix).name, '..') == 0))
  	    files=strvcat(files,ff(ix).name);
      end
   end

files=sortrows(files);

fstrep=figure('Name','Stations dans le repertoire de donnees',...
          'Color',[ 0.8 0.8 0.8],...
	  'Units','normalized', ...
          'NumberTitle','off',...
          'MenuBar','none',...
          'Position',[0.5 0.35 0.35  0.3]);


% repertoire 
% ----------
uicontrol('Style','Text',...
	     'Units','normalized', ...
	     'Parent',fstrep, ...
             'String','Repertoire ',...
	     'FontSize',12, ...
	     'BackgroundColor',[ 0.8 0.8 0.8], ...
             'HorizontalAlignment','left', ...
             'Position',[0.03 0.90 0.24 0.06]);

uicontrol('Style','Edit',...
	     'Units','normalized', ...
	     'Parent',fstrep, ...
	     'FontSize',12, ...
             'String',REPLECT, ...
	     'BackgroundColor',[0.9 0.9 0.9], ...
             'HorizontalAlignment','left', ...
             'Position',[0.03 0.78 0.72 0.1]);



% boutons ajouter et supprimer
% ----------------------------

fstrep_aj=uicontrol('Parent',fstrep, ...
		'Style','pushbutton',...
	        'BackgroundColor', [0.701961 0.701961 0.701961], ...
	        'Units','normalized', ...
                'String','Ajouter',...
	        'Callback','str_CBAjou', ...
	        'FontSize',12, ...
                'Position',[0.40 0.45 0.19 0.1]);

fstrep_sup=uicontrol('Parent',fstrep, ...
		'Style','pushbutton',...
	        'BackgroundColor', [0.701961 0.701961 0.701961], ...
	        'Units','normalized', ...
	        'Callback','str_CBSupp', ...
                'String','Supprimer',...
	        'FontSize',12, ...
                'Position',[0.40 0.30 0.19 0.1]);



% liste des fichiers du repertoire (txt)
% --------------------------------------

uicontrol('Parent',fstrep, ...
	'Units','normalized', ...
	'BackgroundColor',[ 0.8 0.8 0.8], ...
	'FontSize',12, ...
	'HorizontalAlignment','left', ...
	'Position',[0.03 0.62 0.4 0.06], ...
	'String','Fichiers presents', ...
	'Style','text');


% liste des fichiers du repertoire (listbox)
% ------------------------------------------

uicontrol('Parent',fstrep, ...
	     'Style','ListBox',...
	     'Units','normalized', ...
	     'BackgroundColor',[0.9 0.9 0.9], ...
             'String',files,...
	     'FontSize',12, ...
             'Position',[0.03 0.22 0.35 0.37],...
	     'Tag','list_fics', ...
             'Max',length(files));



% liste des fichiers selectionnes (txt)
% -------------------------------------

uicontrol('Parent',fstrep, ...
	'Units','normalized', ...
	'BackgroundColor',[ 0.8 0.8 0.8], ...
	'FontSize',12, ...
	'HorizontalAlignment','right', ...
	'Position',[0.57 0.62 0.4 0.06], ...
	'String','Fichiers selectionnes', ...
	'Style','text');


% liste des fichiers selectionnes(listbox)
% ----------------------------------------

uicontrol('Parent',fstrep, ...
		'Style','ListBox',...
		'Units','normalized', ...
		'BackgroundColor',[1 1 1], ...
	     	'FontSize',12, ...
            	'String',nomfsel,...
            	'Position',[0.62 0.22 0.35 0.37],...
 		'UserData',suf, ...
 		'Tag','list_fsels');

nbf = length(files);
nomfsel = char(files);	


%------------------------------------
% validation

uicontrol('Parent',fstrep, ...
	'Units','normalized', ...
	'BackgroundColor', [0.701961 0.701961 0.701961], ...
		'Style','PushButton',...
	        'FontSize',12, ...
                'String','OK',...
	'Position',[0.03 0.04 0.17 0.1], ...
                'Callback',['listrep_OK,', ...
                            'if isempty(NOM_FILES),', ...
                                 'h=warndlg(''Aucun fichier selectionne'',''Erreur'');', ...
                                'waitfor(h),', ... 
                             'else,', ...
                               'verif_station,', ...
                               'recupStations, close,', ...
                             'end;']);

uicontrol('Parent',fstrep, ...
	'Units','normalized', ...
	'BackgroundColor', [0.701961 0.701961 0.701961], ...
	'Style','Pushbutton',...
	'FontSize',12, ...
        'String','Annuler',...
	'Position',[0.8 0.04 0.17 0.1], ...
        'Callback','close');

% si le repertoire de donnees n'existe pas

else
	h=errordlg(msgerr,'Erreur','on');
	waitfor(h);
end;



