function stat_cat(masq_cat)
          
% Fenêtre de saisie pour un fichier catalogue

globalVarEtiquni;

globalVarDef;

globalRepDef;  

a = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Name','Choix d''un fichier Catalogue', ...   
        'NumberTitle','off',...
        'MenuBar','none',...
	'Position',[0.448785 0.502222 0.5 0.2]);


uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'HorizontalAlignment','left', ...
	'Position',[0.03 0.44 0.3 0.15], ...
	'String','Fichier Catalogue', ...
	'Style','text');

nom_cat = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
        'Callback',['NOMFIC_CAT=get(gco,''String'');', ...
                    'n=length(NOMFIC_CAT);', ...
                    'if NOMFIC_CAT(n-2:n) == ''cat'',', ...
                    'n = n-4;', ...
                    'end;', ...
                    'sufcat = ''.cat'';', ...
                    'NOMFIC_CAT=[NOMFIC_CAT(1:n) sufcat];'], ...
	'Position',[0.3 0.47 0.2 0.13], ...
	'Style','edit');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',14, ...
	'Position',[0.5 0.44 0.1 0.15], ...
	'String','.cat', ...
	'Style','text');

% button ...
% ----------

hchoixcat = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'FontSize',15, ...
	'Position',[0.600694 0.483333 0.0885417 0.105556], ...
	'String','...', ...
	'Style','Pushbutton');

% initialisation du Callback du choix du fichier Catalogue

Callchoix = ['global nom_cat NOMFIC_CAT masq_cat,',...
             'globalRepDef;', ...
             '[NOMFIC_CAT,DIRSERV] = sel_fic(''Choisir un fichier .cat'',masq_cat,DIRSERV);', ... 
             'set(nom_cat,''String'',NOMFIC_CAT(1:length(NOMFIC_CAT)-4));'];

set(hchoixcat,'CallBack',Callchoix);



uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback',['global ETIQ NOMFIC_CAT , globalRepDef,', ...
                    'if length(NOMFIC_CAT)<5,', ...
                    '   h = warndlg(''Vous devez saisir un nom de fichier Catalogue.'',''Erreur'');', ...
                    '   waitfor(h);', ...
                    ' else,', ...
                    '   NOMFIC_CAT=[DIRSERV  NOMFIC_CAT];', ...
                    '   if  ~exist(NOMFIC_CAT),', ...
                    '     h = warndlg(''Fichier Catalogue inexistant'',''Erreur'');', ...
                    '     waitfor(h);', ...
                    '   else,', ...
                    '     load_cat;close;', ...
                    '     existe_files;', ...
                    '     if NBFILES > 0,', ...
                    '        verif_station , recupStations,end,', ...
                    '   end,', ...
                    'end,'], ...
	'FontSize',12, ...
	'Position',[0.03 0.1 0.2 0.15], ...
	'String','OK', ...
	'Style','Pushbutton');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback',['global NOMFIC_CAT;', ...
                    'NOMFIC_CAT = '''';', ...
                    'close'], ...
	'FontSize',12, ...
	'Position',[0.7 0.1 0.2 0.15], ...
	'String','Annuler', ...
	'Style','Pushbutton');
