function   ajo_lisscren (); 

% determination du parametre 'largeur'
% dans le cas de lissage creneau
% ------------------------------------


globalVarDef;

globalVarEtiquni;

globalajo;

larg_c = '';


a = figure('Units','normalized', ...
	   'Color',[0.8 0.8 0.8], ...
	   'Position',[0.64 0.4 0.31 0.15], ...
 	   'Name','Lissage Creneau', ...
           'NumberTitle','off',...
           'MenuBar','none');

uicontrol('Parent',a, ...
	   'Units','normalized', ...
	   'BackgroundColor',[1 1 1], ...
           'String',C_LARG_DEF, ...
           'Callback','global larg_c;larg_c  = str2num(get(gco,''String''));', ...
           'Fontsize',12, ...
	   'Position',[0.6 0.71 0.1 0.18], ...
	   'Style','edit');

uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Largeur', ...
        'BackgroundColor',[0.8 0.8 0.8], ...
        'Fontsize', 12, ...
	'Position',[0.2 0.71 0.26 0.18], ...
	'Style','text');


% bouton OK
% --------------
uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Ok', ...
        'Callback',['global larg_c ;P1_LISS  = larg_c,', ...
                    'if  isempty(larg_c),', ...
                        'P1_LISS  = C_LARG_DEF;', ...
                     'end;', ...
                    'P2_LISS  = zeros;', ...
                    'TYP_LISS(1:11) = ''Creneau    '';', ...
                    'close,'], ...
        'Fontsize', 12, ...
	'Position',[0.15 0.26 0.21 0.21], ...
	'Style','Pushbutton');


% bouton Annuler
% --------------
uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Annuler', ...
        'Callback',['TYP_LISS(1:11) = '' '';', ...
                    'P1_LISS = zeros;', ...
                    'P2_LISS = zeros;', ...
                    'close,'] , ...
        'Fontsize', 12, ...
	'Position',[0.6 0.26 0.21 0.21], ...
        'Style','Pushbutton');


% bouton AIDE pour demi-largeur du filtre
% ---------------------------------------


uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String', 'Aide', ...
        'Callback', 'aide(2)', ...
        'Fontsize', 12, ...
	'Position',[0.8 0.71 0.1 0.18]);

