function   ajo_lissstand ()

% determination des parametres
% Periode de coupure et ordre du filtre 
% dans le cas de lissage Butterworth
% --------------------------------------

globalVarDef;

globalajo;

period_b = '';
ordr_b   = '';


a = figure('Units','normalized', ...
	   'Color',[0.8 0.8 0.8], ...
	   'Position',[0.64 0.4 0.31 0.15], ...
 	   'Name','Lissage Butterworth', ...
           'NumberTitle','off',...
           'MenuBar','none');


uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'String', B_PERIOD_DEF, ...
        'Callback', 'global period_b;period_b = str2num(get(gco,''String''));', ...
        'Fontsize', 12, ...
	'Position',[0.6 0.71 0.1 0.18], ...
	'Style','edit');

uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Fréquence', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
        'Fontsize', 12, ...
	'Position',[0.2 0.71 0.26 0.18], ...
	'Style','text');

% bouton AIDE pour période de coupure
% -------------------------------------


uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String', 'Aide', ...
        'Callback', 'aide(7)', ...
        'Fontsize', 12, ...
	'Position',[0.8 0.71 0.1 0.18]);


% ordre du filtre
% ---------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Ordre du filtre', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
        'Fontsize', 12 , ...
	'Position',[0.20 0.29 0.28 0.2], ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'String',B_ORDR_DEF , ...
        'Callback', 'global ordr_b;ordr_b = str2num(get(gco,''String''));', ...
        'Fontsize', 12, ...
	'Position',[0.6 0.35 0.1 0.18], ...
	'Style','edit');

% bouton AIDE pour ordre
% ------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String', 'Aide', ...
        'Callback', 'aide(13)', ...
        'Fontsize', 12, ...
	'Position',[0.8 0.35 0.1 0.18]);


% bouton Annuler
% --------------
uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Annuler', ...
        'Callback',['P1_LISS = zeros;', ...
                    'P2_LISS = zeros;', ...
                    'TYP_LISS(1:11) = '' '';', ...
                    'close,'], ...
        'Fontsize', 12, ...
	'Position',[0.6 0.06 0.21 0.21], ...
        'Style','Pushbutton');

% bouton Ok
% ---------
uicontrol('Parent',a, ...
	'Units','normalized', ...
        'String','Ok', ...
        'Callback',['global period_b ordr_b;', ...
                    'if (isempty(period_b)),', ...
                       'P1_LISS = B_PERIOD_DEF;', ...
                         'else,', ...
                       'P1_LISS = period_b;end;', ...
                    'if (isempty(ordr_b)),', ...
                       'P2_LISS = B_ORDR_DEF;', ...
                         'else,', ...
                       'P2_LISS = ordr_b;end;', ...
                    'TYP_LISS(1:11) = ''Butterworth'';', ...
                    'close,'], ...
        'Fontsize', 12, ...
	'Position',[0.2 0.06 0.21 0.21], ...
        'Style','Pushbutton');
