function idec = bv2_decal();

% ---------------------------------------------
% bv2_decal : C.Lagadec - nov.98
%                          
% fonction appelée par calc_param
% Demande  des fichiers clc
% ---------------------------------------------

globalVarEtiquni;

global idec DEC_BV2;

idec = '';
DEC_BV2 = 1;


fig_decal = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Name','Calcul du parametre Frequence de Brunt-Vaisala', ...
        'NumberTitle','off', ...
        'MenuBar','none',...
	'Position',[0.473958 0.531111 0.384549 0.156667]);


b = uicontrol('Parent',fig_decal, ...
	'Units','normalized', ...
	'FontSize',12, ...
        'Callback',['global idec DEC_BV2,', ...
                    'if isempty(idec),' ...
                      'idec = DEC_BV2;', ...
                    'end,close,'], ...
	'Position',[0.77 0.18 0.15 0.25], ...
	'String','OK');

b = uicontrol('Parent',fig_decal, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.025 0.57 0.60 0.22], ...
	'String','Decalage en nombre de niveaux ', ...
	'Style','text');

b = uicontrol('Parent',fig_decal, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
        'String', DEC_BV2, ...
        'HorizontalAlignment','center', ...
        'CallBack','global idec,idec=str2num(get(gco,''String''));', ...
	'Position',[0.65 0.59 0.14 0.21], ...
	'Style','edit');

uiwait(fig_decal);
