function messerr=charg_ajo ()
%
%---------------------------------------------------------------
% Saisie du nom et lecture d'un fichier des parametres à ajouter 
% C.Lagadec - Nov 98
%---------------------------------------------------------------
%                   
  
globalVarEtiquni;

globalRepDef;
globalajo;

global nom_ajo ; 

messerr= '';

a = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Name','Choix d''un fichier .ajo', ...   
        'NumberTitle','off',...
        'MenuBar','none',...
	'Position',[0.448785 0.502222 0.5 0.2]);


uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'HorizontalAlignment','left', ...
	'Position',[0.03 0.47 0.4 0.116], ...
	'String','Fichier des paramètres à calculer', ...
	'Style','text');

nom_ajo = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
        'Callback',['global nomficajo; nomficajo=get(gco,''String'');', ...
                    'n=length(nomficajo);', ...
                    'nomficajo=[nomficajo(1:n) ''.ajo''];'], ...
	'Position',[0.467 0.467 0.206 0.127], ...
	'Style','edit');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.69 0.47 0.08 0.127], ...
	'String','.ajo', ...
	'Style','text');

hchoixcat = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'FontSize',15, ...
	'Position',[0.8 0.483333 0.0885417 0.105556], ...
	'String','...', ...
	'Style','Pushbutton');

% initialisation du Callback du choix du fichier Options

Callchoix = ['global nom_ajo nomficajo,',...
             '[nomficajo,DIRSERV] = sel_fic(''Choisir un fichier .ajo'',''*.ajo'',DIRSERV);', ... 
             'set(nom_ajo,''String'',nomficajo(1:length(nomfic)-4));'];

set(hchoixcat,'CallBack',Callchoix);



uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
                    'Callback',['global nomficajo;nomficajo=[DIRSERV nomficajo];', ...
                                '[messerr] =lect_ajo(nomficajo);close;'], ...
	'FontSize',12, ...
	'Position',[0.03 0.1 0.2 0.15], ...
	'String','OK', ...
	'Style','Pushbutton');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','global nomficajo;nomficajo='''';close;', ...
	'FontSize',12, ...
	'Position',[0.7 0.1 0.2 0.15], ...
	'String','Annuler', ...
	'Style','Pushbutton');

uiwait(a);
