function choix_envir_ajo ()

% --------------------------------------------------------------
% choix des repertoires de lecture et d'ecriture
% 
% Version speciale AJOCLC : REPECR obligatoirement egal a REPLECT
%
% --------------------------------------------------------------


% repertoires de lecture et d'ecriture
globalRepDef;

serv = DIRSERV;

DIRSERV = '';

a = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'MenuBar','none', ...
	'Name','Environnement de travail', ...
	'NumberTitle','off', ...
	'Position',[0.44 0.5 0.45 0.22]);

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','DIRSERV = [REPLECT ''service/''];close,choix_repserv,', ...
	'FontSize',13, ...
	'ListboxTop',0, ...
	'Position',[0.13 0.1 0.22 0.16], ...
	'String','Ok');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
        'Callback',['REPLECT=get(gco,''String'');', ...
                    'if ~exist(REPLECT,''dir''),', ...
                           'h = warndlg(''Le repertoire n''''existe pas  !'',''Erreur'');', ...
                           'waitfor(h);', ...
                         'else,', ...
                           'REPLECT = deblank(REPLECT);', ...
                           'ir = length(REPLECT);', ...
                           'if  REPLECT(ir) ~= ''/'',', ...
                              'REPLECT = [REPLECT ''/''];', ...
                           'end;', ...
                           'REPECR  = REPLECT;', ...
                           'DIRSERV = [REPLECT ''service/''];', ...
                     'end;'], ...
 	'FontSize',11, ...
	'Position',[0.40 0.75 0.60 0.14], ...
	'String',REPLECT,...
        'HorizontalAlignment','left', ...
	'Style','edit');


% Pushbutton de sortie d'ecran
% ----------------------------

% -> Annuler

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','close', ...
	'FontSize',13, ...
	'Position',[0.73 0.1 0.22 0.16], ...
	'String','Annuler');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...	
        'Position',[0.007 0.758 0.37 0.11], ...
	'FontSize',12, ...
	'ListboxTop',0, ...
	'String','Repertoire de lecture', ...
	'Style','text');
