function choix_param_calc()
%
%%%%%%%%%%%%%
%
% Choix des parametres a calculer
% 
% C.Lagadec : Nov. 97
%
%%%%%%%%%%%%

globalVarEtiquni;

globalVarDef;

globalajo;

global PARCALC;
global NOMLISS;

P1_LISS = 0;
P2_LISS = 0;
TYP_LISS(1:11) = ' ';


NOMLISS =['Creneau    ';'Lanczos    ';'Butterworth';'Aucun      '];

% Fenetre de saisie des parametres a calculer
% -------------------------------------------
a = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Name','Choix des parametres', ...
        'NumberTitle','off',...
        'MenuBar','none',...
	'Position',[0.385 0.5 0.56 0.45]);
figure(a);

% --------------------
% Parametres existants
% --------------------

% Parametres  (txt)
uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontSize',13, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[0.03 0.92 0.42 0.06], ...
	'String','Parametres existants', ...
	'Style','text');

% Codes  et labels des parametres existants (listbox)
% -----------------------------------------

ligpp = [];
lblanc = blanks(10);

if (NPARP_TOT > 0)

	for i=1:NPARP_TOT
		lig1pp = sprintf('%1c%s%s%s', PRESENCP_TOT (i), CODPARP_TOT (i, :), lblanc, LABPARP_TOT (i, :));
		if (i == 1)
			ligpp = lig1pp;
		else
			ligpp = char(ligpp, lig1pp);
		end
	end
end

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.791 0.791 0.791], ...
	'Position',[0.009 0.37 0.48 0.50], ...
	'FontSize',11, ...
	'Style','listbox', ...     
        'String',ligpp, ...
        'Max',length(ligpp));

% -----------------------------------------
% Codes et labels des parametres a calculer
% -----------------------------------------

% Parametres  (txt)
% -----------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',13, ...
	'Position',[0.5 0.92 0.42 0.06], ...
	'String','Parametres a calculer', ...
	'Style','text');

ligpp = [];
lblanc = blanks(10);
if (NBPARCALC > 0)
	
	for i=1:NBPARCALC
		lig1pp = sprintf('%s%s%s', CODES_CALC (i, :), lblanc, LABELS_CALC (i, :));
		if (i == 1)
			ligpp = lig1pp;
		else
			ligpp = char(ligpp, lig1pp);
		end
	end
end


% Codes et labels des parametres a calculer (listbox)
% ---------------------------------------------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[0.51 0.37 0.48 0.50], ...
	'FontSize',11, ...
        'Callback',['globalajo, global PARCALC,', ...
                    'valc = get(gco, ''Value'');',...
                    'param=CODES_CALC(get(gco,''Value''),:);', ...
                    'set(PARCALC,''String'',param);'], ...
        'String',ligpp, ...
	'Style','listbox', ...
	'Value',1);


% Parametre choisi
% ----------------


uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.05 0.2 0.4 0.06], ...
	'String','Parametre a calculer', ...
	'Style','text');

PARCALC = uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
    'Callback',('param=get(gco,''String'');'), ...
	'Position',[0.45 0.2 0.1 0.06], ...
	'Style','edit');

% Lissage  (txt)
% -------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontSize',13, ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'Position',[0.50 0.26 0.5 0.08], ...
	'String','Lissage', ...
	'Style','text');

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontSize',12, ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Position',[0.65 0.2 0.2 0.08], ... 
	'String',NOMLISS, ...
	'Style','popupmenu', ... 
        'Value',4, ...
        'Callback',['choixliss = get(gco,''value'');', ...
                     'switch choixliss,', ...
                     'case 1,ajo_lisscren ;', ...
                     'case 2,ajo_lisslanc;', ...
                     'case 3,ajo_lissstand;', ...
                     'end;']);



% Ok (push)
% ---------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'FontSize',12, ...
        'Callback', ['if isempty(param),', ...
                       'h=warndlg(''Vous devez selectionner un parametre.'',''Erreur'');', ...
                      'else,', ...
                        'close,', ...
                     'ajouparam(param),end;'], ...
	'Position',[0.05 0.02 0.15 0.07], ...
	'String','OK');

% Quitter (push)
% --------------

uicontrol('Parent',a, ...
	'Units','normalized', ...
	'FontSize',12, ...
        'Callback','close',...
	'Position',[0.75 0.02 0.15 0.07], ...
	'String','Fin ajout');
