function pref_hdy = hdy_nivref();

% ---------------------------------------------
% hdy_nivref : C.Lagadec - fev.99
%                          
% fonction appelee par calc_param
%
% demande du niveau de refernce dans le cas
% de calcul de la hauteur dynamique
% ---------------------------------------------

globalVarEtiquni;

global pref_hdy PREF_HDY;

pref_hdy = '';
PREF_HDY = 0;


fig_nivref = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Name','Calcul du parametre Hauteur Dynamique', ...
        'NumberTitle','off', ...
        'MenuBar','none',...
	'Position',[0.473958 0.531111 0.384549 0.156667]);


b = uicontrol('Parent',fig_nivref, ...
	'Units','normalized', ...
	'FontSize',12, ...
        'Callback',['global pref_hdy PREF_HDY,', ...
                    'if isempty(pref_hdy),' ...
                      'pref_hdy = PREF_HDY;', ...
                    'end,close,'], ...
	'Position',[0.77 0.18 0.15 0.25], ...
	'String','OK');

b = uicontrol('Parent',fig_nivref, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',12, ...
	'Position',[0.025 0.57 0.60 0.22], ...
	'String','Niveau de reference (en decibars) ', ...
	'Style','text');

b = uicontrol('Parent',fig_nivref, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
        'String', PREF_HDY, ...
        'HorizontalAlignment','center', ...
        'CallBack','global pref_hdy,pref_hdy=str2num(get(gco,''String''));', ...
	'Position',[0.65 0.59 0.14 0.21], ...
	'Style','edit');

uiwait(fig_nivref);
