function sauv_ajo ()
%
%%%%%%%%%%%
%
% Creation d'une liste de param calcules (pour AJOCLC)
%  - sauvegarde du fichier .ajo dans 'service'
%
% C.Lagadec - Fev 99
%
%%%%%%%%%
%                   

globalRepDef;

global  nom_ajo;

hajo = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Name','Sauvegarde du fichier .ajo', ...   
        'NumberTitle','off',...
        'MenuBar','none',...
	'Position',[0.5 0.55 0.5 0.2]);


uicontrol('Parent',hajo, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',13, ...
	'HorizontalAlignment','left', ...
	'Position',[0.03 0.44 0.5 0.15], ...
	'String','Fichier des parametres calcules', ...
	'Style','text');

nom_ajo = uicontrol('Parent',hajo, ...
	'Units','normalized', ...
	'BackgroundColor',[1 1 1], ...
	'FontSize',12, ...
        'Callback',['global ficajo,', ...
                    'ficajo=get(gco,''String'');', ...
                    'n=length(ficajo);', ...
                    'if ficajo(n-2:n) == ''ajo'',', ...
                    'n = n-4;', ...
                    'end;', ...
                    'sufajo = ''.ajo'';', ...
                    'ficajo=[ficajo(1:n) sufajo];'], ...
	'Position',[0.5 0.47 0.2 0.13], ...
	'Style','edit');

uicontrol('Parent',hajo, ...
	'Units','normalized', ...
	'BackgroundColor',[0.8 0.8 0.8], ...
	'FontSize',13, ...
	'Position',[0.7 0.44 0.1 0.15], ...
	'String','.ajo', ...
	'Style','text');

hchoixcat = uicontrol('Parent',hajo, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'FontSize',15, ...
	'Position',[0.8 0.483333 0.0885417 0.105556], ...
	'String','...', ...
	'Style','Pushbutton');

% initialisation du Callback du choix du fichier Options

Callchoix = ['global nom_ajo ficajo,',...
             '[ficajo,DIRSERV] = sel_fic(''Choisir un fichier .ajo'',''*.ajo'',DIRSERV);', ... 
             'set(nom_ajo,''String'',ficajo(1:length(ficajo)-4));'];

set(hchoixcat,'CallBack',Callchoix);



uicontrol('Parent',hajo, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback',['global ficajo DIRSERV ,', ...
                    'ficajo  = [DIRSERV  ficajo];', ...
                    'ecr_ajo(ficajo);', ...
                    'close;'], ...
	'FontSize',12, ...
	'Position',[0.03 0.1 0.2 0.15], ...
	'String','Ok', ...
	'Style','Pushbutton');

uicontrol('Parent',hajo, ...
	'Units','normalized', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Callback','close', ...
	'FontSize',12, ...
	'Position',[0.7 0.1 0.2 0.15], ...
	'String','Annuler', ...
	'Style','Pushbutton');
uiwait(hajo);
