function arrowdlg(command)
if(nargin < 1)
	BackgroundColor = 'b';
	ForegroundColor = [1 1 1];
	Widgetbground = .702*ones(1,3);
	Widgetfground = [0 0 0];
	figpos = [100 350 320 200];
	titlefig = figure('Units','Points',...
	                  'Color',BackgroundColor,...
	                  'Position',figpos,...
					  'Name','Arrows',...
					  'NextPlot','new',...
					  'Resize','off',...
					  'NumberTitle','off');
	axis off;
	set(gca,'position',[0 0 1 1]);
	axis(axis);
	top = figpos(4);
	right = figpos(3);
	leftmargin = 10;
	topmargin = 30;
	vspace = 10;
	hspace = 5;
	edsize = objsize('edit',5);
	txtsize = textlen('Base Angle:');
	position = [leftmargin top-topmargin-edsize(2) txtsize(1) edsize(2)];
	uicontrol(titlefig,'BackgroundColor',BackgroundColor,...
						'ForegroundColor',ForegroundColor,...
						'Style','text',...
						'String','Base Angle:',...
						'Units','points',...
						'Position',position);
	position(2) = position(2) - position(4) - vspace;
	uicontrol(titlefig,'BackgroundColor',BackgroundColor,...
						'ForegroundColor',ForegroundColor,...
						'Style','text',...
						'String','Tip Angle:',...
						'Units','points',...
						'Position',position);
	position = [leftmargin+position(3)+hspace top-topmargin-edsize(2) objsize('edit',5)];
	BangEdit = uicontrol(titlefig,'BackgroundColor',Widgetbground,...
						'ForegroundColor',Widgetfground,...
						'Style','edit',...
						'Units','points',...
						'String','90',...
						'Position',position,...
						'Callback','arrowdlg(''DrawArrow'')',...
						'Tag','bang');
	position(2) = position(2) - position(4) - vspace;
	TangEdit = uicontrol(titlefig,'BackgroundColor',Widgetbground,...
						'ForegroundColor',Widgetfground,...
						'Style','edit',...
						'String','16',...
						'Units','points',...
						'Position',position,...
						'Callback','arrowdlg(''DrawArrow'')',...
						'Tag','tang');
	txtsize = textlen('Length:');
	position = [position(1)+position(3)+hspace top-topmargin-edsize(2) txtsize(1) edsize(2)];
	uicontrol(titlefig,'BackgroundColor',BackgroundColor,...
						'ForegroundColor',ForegroundColor,...
						'Style','text',...
						'String','Length:',...
						'Units','points',...
						'Position',position);
	position(2) = position(2) - position(4) - vspace;
	uicontrol(titlefig,'BackgroundColor',BackgroundColor,...
						'ForegroundColor',ForegroundColor,...
						'Style','text',...
						'String','Width:',...
						'Units','points',...
						'Position',position);
	position = [position(1)+position(3)+hspace top-topmargin-edsize(2) txtsize(1) edsize(2)];
	LengthEdit = uicontrol(titlefig,'BackgroundColor',Widgetbground,...
						'ForegroundColor',Widgetfground,...
						'style','edit',...
						'Units','points',...
						'String','16',...
						'Position',position,...
						'Callback','arrowdlg(''DrawArrow'')',...
						'Tag','length');
	position(2) = position(2) - position(4) - vspace;
	WidthEdit = uicontrol(titlefig,'BackgroundColor',Widgetbground,...
						'ForegroundColor',Widgetfground,...
						'style','edit',...
						'String','0',...
						'Units','points',...
						'Position',position,...
						'Callback','arrowdlg(''DrawArrow'')',...
						'Tag','width');

	txtsize = textlen('Blah Blah');
	position = [position(1)+position(3)+2*hspace top-topmargin textlen('Arrow Plane:') edsize(2)];
	uicontrol(titlefig,'Style','Text',...
			  'ForegroundColor',ForegroundColor,...
			  'BackgroundColor',BackgroundColor,...
			  'String','Arrow Plane:',...
			  'Units','points',...
			  'Position',position);
	position = [position(1) top-topmargin-edsize(2) txtsize(1) edsize(2)];
	uicontrol(titlefig,'Style','radio',...
			  'ForegroundColor',ForegroundColor,...
			  'BackgroundColor',BackgroundColor,...
			  'Value',1,...
			  'String','Auto',...
			  'Units','points',...
			  'Callback','arrowdlg(''Radio'')',...
			  'Position',position);
	position(2) = position(2) - position(4) - vspace;
	tpos = position;
	uicontrol(titlefig,'Style','radio',...
			  'ForegroundColor',ForegroundColor,...
			  'BackgroundColor',BackgroundColor,...
			  'String',' XY ',...
			  'Units','points',...
			  'Callback','arrowdlg(''Radio'')',...
			  'Position',position);
	position = [position(1)+position(3)+hspace top-topmargin-edsize(2) txtsize(1) edsize(2)];
	uicontrol(titlefig,'Style','radio',...
			  'ForegroundColor',ForegroundColor,...
			  'BackgroundColor',BackgroundColor,...
			  'String',' YZ ',...
			  'Units','points',...
			  'Callback','arrowdlg(''Radio'')',...
			  'Position',position);
	position(2) = position(2) - position(4) - vspace;
	uicontrol(titlefig,'Style','radio',...
			  'ForegroundColor',ForegroundColor,...
			  'BackgroundColor',BackgroundColor,...
			  'String',' XZ ',...
			  'Units','points',...
			  'Callback','arrowdlg(''Radio'')',...
			  'Position',position);
	position = [tpos(1) tpos(2)-edsize(2)-2*vspace 80 edsize(2)+5];
	uicontrol(titlefig,'Style','pushbutton',...
			  'ForegroundColor',Widgetfground,...
			  'BackgroundColor',Widgetbground,...
			  'String','Apply',...
			  'Units','points',...
			  'Callback','arrowdlg(''Apply'')',...
			  'Position',position);
	position(2) = position(2) - position(4) - vspace;
	uicontrol(titlefig,'Style','pushbutton',...
			  'ForegroundColor',Widgetfground,...
			  'BackgroundColor',Widgetbground,...
			  'String','Cancel',...
			  'Units','points',...
			  'Callback','arrowdlg(''Cancel'')',...
			  'Position',position);
	position(2) = position(2) - position(4) - vspace;
	uicontrol(titlefig,'Style','pushbutton',...
			  'ForegroundColor',Widgetfground,...
			  'BackgroundColor',Widgetbground,...
			  'String','OK',...
			  'Units','points',...
			  'Callback','arrowdlg(''OK'')',...
			  'Position',position);

    axes('Units','Points',...
	     'Position', [20 20 200 100],...
		 'Xlim',[0 1],'Ylim',[0 1],...
		 'XTickLabelMode','manual',...
		 'XTickLabels',[],...
		 'YTickLabelMode','manual',...
		 'YTickLabels',[],...
		 'XColor',BackgroundColor,...
		 'YColor',BackgroundColor);
	set(gcf,'UserData',arrow('start',[.2 .5],'stop',[.8 .5],...
							 'BaseAngle',str2num(get(findobj(gcf,'tag','bang'),'string')),...
							 'TipAngle',str2num(get(findobj(gcf,'tag','tang'),'string')),...
							 'Length',str2num(get(findobj(gcf,'tag','length'),'string')),...
							 'Width',str2num(get(findobj(gcf,'tag','width'),'string'))));
elseif(strcmp(command,'DrawArrow'))
	arrow_handle = get(gcf,'UserData');
	arrow(arrow_handle,...
		  'start',[.2 .5],...
		  'stop',[.8 .5],...
		  'BaseAngle',str2num(get(findobj(gcf,'tag','bang'),'string')),...
		  'TipAngle',str2num(get(findobj(gcf,'tag','tang'),'string')),...
		  'Length',str2num(get(findobj(gcf,'tag','length'),'string')),...
		  'Width',str2num(get(findobj(gcf,'tag','width'),'string')));
elseif(strcmp(command,'Radio'))
	ThisButton = gco;
	OtherButtons = findobj(gcf,'Style','radiobutton');
	OtherButtons = OtherButtons(find(OtherButtons ~= ThisButton));
	set(ThisButton,'Value',1);
	set(OtherButtons,'Value',0);
elseif(strcmp(command,'Cancel'))
	delete(gcf);
elseif(strcmp(command,'Apply'))
	DatObjs = get(findobj('Name','Draw Tools'),'UserData');
	SelectList = get(DatObjs(3),'UserData');
	Defaults = get(DatObjs(5),'UserData');
	BaseAngle = str2num(get(findobj(gcf,'Tag','bang'),'String'));
	TipAngle = str2num(get(findobj(gcf,'Tag','tang'),'String'));
	Length = str2num(get(findobj(gcf,'Tag','length'),'String'));
	Width = str2num(get(findobj(gcf,'Tag','width'),'String'));
	NormString = get(findobj(gcf,'Style','radiobutton','Value',1),'String');
	if(strcmp(NormString,' XY '))
		NormDir = [0 0 1];
	elseif(strcmp(NormString,' XZ '))
		NormDir = [0 1 0];
	elseif(strcmp(NormString,' YZ '))
		NormDir = [1 0 0];
	else 
		NormDir = [0 0 0];
	end
	if(isempty(SelectList))
		ArrowDefs = get(Defaults(11),'UserData');
		ArrowDefs(1:7) = [Length Width BaseAngle TipAngle CrossDir];
		set(Defaults(11),'UserData',ArrowDefs);
	else
		Arrows = findobj(SelectList(:,1),'Tag','Arrow');
		if(~isempty(Arrows))
			arrow(Arrows,'BaseAngle',BaseAngle,...
							 'TipAngle',TipAngle,...
							 'Length',Length,...
							 'Width',Width,...
							 'Norm',NormDir);
		end
	end
elseif(strcmp(command,'OK'))
	arrowdlg('Apply');
	delete(gcf);
end
